import React,{useState,useRef} from 'react';
import {Bell} from '@phosphor-icons/react/dist/csr/Bell';
export function AlertsPanel({data,act,busy}){
 const [kind,setKind]=useState('high');const [device,setDevice]=useState('');
 const active=data.alarm_episodes.filter(e=>e.resolved==null);
 const submit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));act('alarm_add',{...p,seconds:Number(p.minutes)*60,repeat:Number(p.repeat)*60,unit:data.unit},'Alarm saved')};
 return <section className="feature-screen"><div className="section-heading"><div><p className="eyebrow">A WATCHFUL COMPANION</p><h1>Keep an eye on the important things.</h1><p className="muted">Persistent alarms, clear recovery, and a record of every reminder.</p></div></div>
 <div className="info-box">The local service checks alarms every second while running. In-app reminders need an open view. Browser notifications need permission and browser support; they cannot wake a sleeping computer. No phone push is implied.</div>
 <div className="feature-grid"><article className="feature-card"><h2>Create an alarm</h2><form onSubmit={submit}><label>Label<input name="label" required maxLength={100} placeholder="Chicken target / check the fire"/></label><label>Type<select name="kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="high">Temperature reaches target</option><option value="low">Temperature falls below limit</option><option value="stale">Sensor / reading stops arriving</option><option value="battery">Known battery runs low</option><option value="timer">Timer reminder</option></select></label>{kind!=='timer'&&<><label>Source<select name="device" value={device} onChange={e=>setDevice(e.target.value)}><option value="">Cook readings (manual / selected probe)</option>{data.devices.filter(d=>['ble','bridge'].includes(d.source)).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{kind!=='battery'&&<label>Channel<select name="role"><option value="food">Food</option><option value="ambient">Pit / probe ambient</option></select></label>}</>}
 {kind==='timer'?<label>Minutes from now<input name="minutes" type="number" min="1" max="10080" required defaultValue="15"/></label>:<label>{kind==='stale'?'Maximum sample age (seconds)':kind==='battery'?'Battery threshold (%)':`Threshold (°${data.unit})`}<input key={kind+data.unit} name="threshold" type="number" step="0.1" required defaultValue={kind==='stale'?(device?30:300):kind==='battery'?20:data.unit==='F'?165:74}/></label>}
 <div className="form-pair"><label>Buffer (seconds)<input name="buffer" type="number" min="0" max="3600" defaultValue="0"/></label><label>Repeat (minutes)<input name="repeat" type="number" min="1" max="1440" defaultValue="5"/></label></div><button className="primary" disabled={busy||!data.active||data.active.source==='demo'}>Save alarm</button>{(!data.active||data.active.source==='demo')&&<p className="muted small">Start a real cook to configure alarms.</p>}</form></article>
 <article className="feature-card"><h2>Alarm episodes</h2>{active.length===0&&<p className="muted">No active alarms.</p>}{active.map(e=><div className={'alarm-item '+(e.acknowledged?'ack':'attention')} key={e.id}><strong>{e.label}</strong><small>{e.acknowledged?'Acknowledged':e.snoozed_until>Date.now()/1000?'Snoozed':'Needs attention'} · {new Date(e.opened*1000).toLocaleTimeString()}</small><div className="button-row">{!e.acknowledged&&<><button className="secondary" disabled={busy} onClick={()=>act('alarm_ack',{id:e.id},'Alarm acknowledged')}>Acknowledge</button><button className="secondary" disabled={busy} onClick={()=>act('alarm_snooze',{id:e.id,seconds:300},'Snoozed for 5 minutes')}>Snooze 5m</button></>}</div></div>)}<h2 className="subheading">Rules</h2>{data.alarm_rules.map(r=><div className="list-line" key={r.id}><span>{r.label}<small>{r.kind} · repeat {r.repeat/60}m{r.cook!==data.active?.id?' · other / completed cook':''}</small></span><button className="secondary" disabled={busy} onClick={()=>act('alarm_rule',{id:r.id,enabled:!r.enabled},'Rule updated')}>{r.enabled?'Disable':'Enable'}</button></div>)}<h2 className="subheading">Delivery health</h2><p className="muted small">Background monitor: {data.service_health?.monitor_fresh?'heartbeat received':'not confirmed'}{data.service_health?.at?' · '+new Date(data.service_health.at*1000).toLocaleTimeString():''}. The computer must remain awake.</p><p className="muted small">Server transports: {data.notification_transports.length?data.notification_transports.join(", "):"none configured"}</p>{data.delivery_attempts.slice(0,5).map(d=><div className="list-line" key={d.notice+d.transport}><span>{d.transport} · {d.status}<small>{d.error||""}</small></span></div>)}<h2 className="subheading">Recent reminders</h2>{data.alarm_notices.slice(0,12).map(n=><div className="list-line" key={n.id}><span>{n.label}<small>{n.kind} · {new Date(n.at*1000).toLocaleString()}</small></span></div>)}</article></div></section>
}
export function AlertDelivery({data,onAlerts}){
 const popover=useRef(null);
 React.useEffect(()=>{const dismiss=e=>{if(!popover.current)return;if(e.type==='keydown'&&e.key==='Escape'&&popover.current.open){popover.current.open=false;popover.current.querySelector('summary').focus()}else if(e.type==='pointerdown'&&!popover.current.contains(e.target))popover.current.open=false};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',dismiss);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',dismiss)}},[]);
 const [permission,setPermission]=useState(()=>typeof Notification==='undefined'?'unsupported':Notification.permission);
 const [last,setLast]=useState(()=>Number(sessionStorage.getItem('omapit-last-alarm')||0));
 React.useEffect(()=>{const notices=[...(data?.alarm_notices||[])].sort((a,b)=>a.id-b.id);for(const n of notices){if(n.id<=last||Date.now()/1000-n.at>15)continue;const e=data.alarm_episodes.find(e=>e.id===n.episode);if(!e||e.resolved||e.acknowledged||e.snoozed_until>Date.now()/1000)continue;if(permission==='granted')new Notification('OmaPit · '+n.label,{body:'Check your cook. Open OmaPit to acknowledge.',tag:n.episode});}const max=notices.at(-1)?.id||last;if(max>last){setLast(max);sessionStorage.setItem('omapit-last-alarm',String(max))}},[data,last,permission]);
 const enable=async()=>{if(typeof Notification!=='undefined')setPermission(await Notification.requestPermission())};
 const attention=data.alarm_episodes.some(e=>!e.resolved&&!e.acknowledged&&e.snoozed_until<=Date.now()/1000);
 return <details className="notification-control" ref={popover} onToggle={()=>{if(typeof Notification!=='undefined')setPermission(Notification.permission)}}><summary role="button" aria-label="Notifications" title={'Notifications · '+permission} aria-controls="notification-settings"><Bell size={20}/>{attention&&<span className="notification-dot"/>}</summary><section id="notification-settings" className="notification-popover" aria-label="Notification settings"><h2>Notifications</h2><p className="notification-status">Browser notifications: <strong>{permission}</strong></p><p className="muted small">Reminders need permission and browser support. Keep the cook service awake for background monitoring.</p>{permission==='denied'&&<p className="muted small">Allow notifications in your browser’s site settings to enable them.</p>}<div className="notification-actions"><button className="primary" onClick={enable} disabled={permission==='unsupported'||permission==='granted'||permission==='denied'}>Enable notifications</button><button className="secondary" onClick={()=>{if(permission==='granted')new Notification('OmaPit alarm test',{body:'Notification delivery works in this browser now.'})}} disabled={permission!=='granted'}>Test notification</button><button className="text-button" onClick={()=>{popover.current.open=false;onAlerts?.()}}>Alarm rules & delivery health →</button></div></section></details>

}
