import React,{useState} from 'react';
import {Code} from '@phosphor-icons/react/dist/csr/Code';
import {ShieldCheck} from '@phosphor-icons/react/dist/csr/ShieldCheck';
import './community-settings.css';
const agentPrompt=`Customize OmaPit using AGENTS.md and CUSTOMIZATION.md. Preserve manual mode, active journals, theme roles, accessible controls and reduced motion. Run relevant tests and verify the UI. For hardware reports, follow community/README.md: collect only an explicitly selected device from the local database, keep untested checks marked not-run, validate and prepare a local report. Submit only if the human owner has explicitly enabled submission to a named repository in a local configuration. Never include device addresses, serials, raw packets, credentials, personal notes or cook history. Do not start hardware testing without the owner's request.`;
export function CommunitySettings(){
 const [status,setStatus]=useState('');
 return <section className="community-settings" aria-labelledby="community-title"><div className="logo-setting-heading"><div><p className="eyebrow">OPEN SOURCE · YOUR WORKBENCH</p><h2 id="community-title">Make OmaPit better, together.</h2><p>Customize your setup. Help other cooks connect their hardware.</p></div></div><div className="community-grid"><article><Code size={26} aria-hidden="true"/><h3>Bring your agent</h3><p>Change themes, workflows or adapters using the project’s customization guide. Keep your personal changes separate and contribute improvements when they’re ready.</p><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(agentPrompt);setStatus('Agent instructions copied.')}catch{setStatus('Copy is unavailable. Select the instructions below.')}}}>Copy agent instructions</button><details><summary>Read the instructions</summary><p className="agent-instructions">{agentPrompt}</p></details></article><article><ShieldCheck size={26} aria-hidden="true"/><h3>Share hardware evidence</h3><p>The local benchmark tool prepares model and version details, sample counts, reception gaps and test outcomes. Every untested feature stays clearly marked.</p><span className="community-local-status">Sharing is off by default</span><p className="community-note">Your agent can submit validated reports after you opt in to a named GitHub repository. No background upload runs in this app.</p><details><summary>What stays private?</summary><p>Device addresses, serial numbers, raw Bluetooth packets, account credentials, temperatures, exact timestamps, photos and journal notes are excluded from the report format. Inspect model/version fields before enabling sharing.</p><p>Reports are community evidence. A maintainer reviews them before changing compatibility claims.</p></details></article></div><p className="community-guide">Included in the project: <code>CUSTOMIZATION.md</code> and <code>community/README.md</code>. No submission destination is configured by this page.</p>{status&&<p role="status" className="community-feedback">{status}</p>}</section>
}
