import React,{lazy,Suspense,useState,useRef,useEffect} from 'react';
import {Cube} from '@phosphor-icons/react/dist/csr/Cube';
import {SquaresFour} from '@phosphor-icons/react/dist/csr/SquaresFour';
import {X} from '@phosphor-icons/react/dist/csr/X';
import {ArrowRight} from '@phosphor-icons/react/dist/csr/ArrowRight';
import {Plus} from '@phosphor-icons/react/dist/csr/Plus';
import {Check} from '@phosphor-icons/react/dist/csr/Check';
import {Package} from '@phosphor-icons/react/dist/csr/Package';
import {MagnifyingGlass} from '@phosphor-icons/react/dist/csr/MagnifyingGlass';
import {catalog,species,regionName} from './cutCatalog';
import './cuts.css';
const CutModel=lazy(()=>import('./CutModel').then(m=>({default:m.CutModel})));
export function CutExplorer({data,onPlan,onGuide}){
 const [view,setView]=useState(()=>{try{return localStorage.getItem('omapit-cut-view')==='cards'?'cards':'3d'}catch{return '3d'}}),[details,setDetails]=useState(false);const dialog=useRef(null);
 useEffect(()=>{if(details&&view==='cards')dialog.current?.showModal();else dialog.current?.close()},[details,view]);
 const changeView=next=>{setDetails(false);setView(next);if(next==='cards'){setRegionFilter(null);setQuery('')}try{localStorage.setItem('omapit-cut-view',next)}catch{}};
 const [deerSex,setDeerSex]=useState('buck');
 const [animal,setAnimal]=useState('beef'),[id,setId]=useState('brisket'),[query,setQuery]=useState(''),[regionFilter,setRegionFilter]=useState(null),[weight,setWeight]=useState('4.0'),[weightUnit,setWeightUnit]=useState('lb'),[saved,setSaved]=useState(false);
 const samePanel=(a,b)=>a===b||(animal==='goat'&&['rack','loin'].includes(a)&&['rack','loin'].includes(b));
 const cuts=catalog[animal],selected=cuts.find(c=>c.id===id),selectedRegion=selected?.region||regionFilter||cuts[0].region;
 const shown=cuts.filter(c=>(!regionFilter||samePanel(c.region,regionFilter))&&`${c.name} ${c.region} ${c.description}`.toLowerCase().includes(query.toLowerCase()));
 const choose=c=>{setId(c.id);setSaved(false)};
 const selectRegion=region=>{setQuery('');setRegionFilter(region);const available=cuts.filter(c=>samePanel(c.region,region));if(!available.some(c=>c.id===selected?.id)){if(available.length===1)choose(available[0]);else{setId(null);setSaved(false)}};};
 const changeAnimal=key=>{setAnimal(key);setId(catalog[key][0].id);setQuery('');setRegionFilter(null);setSaved(false)};
 const add=e=>{e.preventDefault();if(!selected)return;const draft={animal,variant:animal==='deer'?deerSex:undefined,cutId:selected.id,name:selected.name,category:selected.category,weight:Number(weight),weightUnit};try{localStorage.setItem('omapit-cut-draft',JSON.stringify(draft));setSaved(true)}catch{setSaved(false);return}onPlan(draft)};
 const inspector=<aside className="cut-inspector" aria-label="Selected cut details"><p className="eyebrow">SELECTED CUT</p><h2>{selected?.name||regionName(selectedRegion)+' region'}</h2><p className="cut-origin">{selected?(selected.region==='whole'?'Whole-bird preparation':'From the '+selected.region+' region'):'Choose a cut from this region below'}</p>{selected?.image&&<img className="cut-photo" src={`/assets/cuts/${selected.image}.webp`} alt={`Illustration of uncooked ${selected.name.toLowerCase()}`}/>}<p className="cut-description">{selected?.description||'This region contains more than one cut. Select a card to see its details and add it to your meal.'}</p>{view==='3d'&&<p className="cut-parent-note">{species[animal].modelReady===false?'The textured model is generated in Meshy; interactive highlights are pending its file import.':animal==='goat'&&['rack','loin'].includes(selectedRegion)?'This sculpture engraves rack and loin as one shared panel. Both cuts highlight that panel.':'The model shows the parent region, not an internal muscle dissection.'}</p>}<form onSubmit={add}><label htmlFor="cut-weight">Planning weight</label><div className="cut-weight"><input id="cut-weight" type="number" min="0.1" max="1000" step="0.1" value={weight} onChange={e=>{setWeight(e.target.value);setSaved(false)}} required/><select aria-label="Planning weight unit" value={weightUnit} onChange={e=>setWeightUnit(e.target.value)}><option>lb</option><option>kg</option></select></div><button className="primary" disabled={!selected}><Package size={19}/>{saved?'Added to meal draft':'Add to meal'}<ArrowRight size={18}/></button></form><p className="cut-parent-note">{data.active?'Saved for your next meal. Your current cook stays intact.':'Review temperatures and timing in meal setup.'}</p><a className="cut-source" href={species[animal].source} target="_blank" rel="noreferrer">Cut reference <ArrowRight size={13}/></a></aside>;
 return <section className={'cut-explorer '+(view==='cards'?'cut-cards-only':'')}><div className="cut-heading"><div><p className="eyebrow">ANATOMICAL WORKBENCH</p><h1>Cut explorer</h1><p className="muted">Explore where a cut comes from. Bring it to your next meal.</p></div><div className="cut-species" aria-label="Animal species">{Object.entries(species).map(([key,v])=><button key={key} aria-pressed={animal===key} className={animal===key?'selected':''} onClick={()=>changeAnimal(key)}>{v.name}</button>)}</div>{animal==='deer'&&<div className="cut-species" aria-label="Deer variant">{['buck','doe'].map(sex=><button key={sex} aria-pressed={deerSex===sex} className={deerSex===sex?'selected':''} onClick={()=>setDeerSex(sex)}>{sex==='buck'?'Buck':'Doe'}</button>)}</div>}<span className="cut-system">U.S. cut names</span></div><div className="cut-prep-links"><button onClick={()=>onGuide('cutting')}>Knives & cutting →</button><button onClick={()=>onGuide('field')}>Hunter’s guide →</button></div>
 <div className="cut-view-toolbar"><p className="muted">{cuts.length} cuts · {species[animal].name}</p><div className="cut-view-switch" role="group" aria-label="Cut explorer view"><button aria-pressed={view==='3d'} onClick={()=>changeView('3d')}><Cube size={17} aria-hidden="true"/>3D view</button><button aria-pressed={view==='cards'} onClick={()=>changeView('cards')}><SquaresFour size={17} aria-hidden="true"/>Cards only</button></div></div>
 {view==='3d'&&<div className="cut-workbench"><div className="cut-stage"><Suspense fallback={<div className="cut-model">Loading 3D viewer…</div>}><CutModel animal={animal} variant={deerSex} region={selectedRegion} onRegion={selectRegion}/></Suspense><div className="region-access" aria-label="Select an animal region">{[...(['chicken','turkey'].includes(animal)?['whole']:[]),...species[animal].regions].map(region=><button key={region} aria-pressed={selectedRegion===region} className={selectedRegion===region?'selected':''} onClick={()=>selectRegion(region)}>{regionName(region)}</button>)}</div></div>
 {inspector}</div>}
 <div className="cut-library-heading"><div><p className="eyebrow">{regionFilter?`${regionName(regionFilter).toUpperCase()} CUTS`:'EXPLORE THE CUTS'}</p>{regionFilter&&<button className="text-button" onClick={()=>setRegionFilter(null)}>Show all cuts</button>}</div><label className="cut-search"><MagnifyingGlass size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cuts…" aria-label="Search cuts"/></label></div>
 <div className="cut-card-rail" aria-label="Meat cuts">{shown.map(c=><button className={'cut-card '+(c.id===selected?.id?'selected':'')} aria-pressed={c.id===selected?.id} key={c.id} onClick={()=>{choose(c);if(view==='cards')setDetails(true)}}>{c.image&&<img src={`/assets/cuts/${c.image}.webp`} alt="" loading="lazy"/>}<span className="cut-card-title">{c.name}{c.id===selected?.id&&<Check size={17}/>}</span><span className="cut-card-origin">{regionName(c.region)}{c.region==='whole'?'':' region'}</span></button>)}{!shown.length&&<p className="muted">No matching cuts. Try another name or show all cuts.</p>}</div><p className="cut-footnote">{view==='3d'?'Anatomical overview · region boundaries are approximate and await butcher review. ':''}Meat images are illustrative.</p>
 {view==='cards'&&<dialog ref={dialog} className="cut-detail-dialog" aria-label="Cut details" onClose={()=>setDetails(false)}><button className="cut-detail-close" aria-label="Close cut details" onClick={()=>dialog.current.close()}><X size={20}/></button>{inspector}</dialog>}
 </section>
}
