import React from 'react';
import {meatBudget} from './meatBudget';
import {dinnerTotals} from './dinnerBudgetStore';
const savedDate=value=>new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(value));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export function DinnerBudget({lines,onEdit,onRemove,download}){
 const sum=dinnerTotals(lines);
 function exportList(){download(['OmaPit · Dinner meat shopping list',...lines.flatMap((l,i)=>{const r=meatBudget(l);return [`\n${i+1}. ${l.cut} · ${l.region} · ${l.quality}`,`${r.raw.toFixed(2)} lb raw · ${money(l.price)} / lb · ${money(r.total)}`,`${l.guests} people eating this meat · ${l.portion} cooked oz each · ${l.yieldPercent}% yield · ${l.reserve}% reserve`,l.mode==='quote'?`Local quote saved ${savedDate(l.savedAt)} · ${l.store||'Store not recorded'} · unverified`:'USDA advertised-price snapshot · October 2, 2026',l.source] }),`\nTotal meat: ${sum.raw.toFixed(2)} lb raw · ${money(sum.total)}`,'Amounts are estimates before pack rounding, tax, sides and fuel. People can overlap across meats; guest counts are not summed.'].join('\n'),'omapit-dinner-shopping-list.txt','text/plain')}
 return <section className="prep-panel dinner-budget"><div className="dinner-budget-heading"><div><p className="eyebrow">YOUR DINNER · SAVED LOCALLY</p><h2>One shopping list. Every meat.</h2></div>{lines.length>0&&<div className="dinner-total"><strong>{money(sum.total)}</strong><span>{sum.raw.toFixed(2)} lb raw · {lines.length} {lines.length===1?'item':'items'}</span></div>}</div><p className="small muted">Set the people eating each meat and its portion before adding. For a mixed menu, split portions across foods; adding two full portions per guest doubles the meat. Saved prices remain fixed until you edit them.</p>{lines.length?<><div className="dinner-lines">{lines.map(l=>{const r=meatBudget(l);return <article key={l.id}><div><h3>{l.cut}</h3><p>{l.region} · {l.quality}</p><small>{l.mode==='quote'?`Local quote · ${l.store||'Store not recorded'} · saved ${savedDate(l.savedAt)}`:'USDA snapshot · Oct 2, 2026'}</small><p>{l.guests} people × {l.portion} cooked oz · {l.yieldPercent}% yield · {l.reserve}% reserve</p></div><div className="dinner-line-cost"><strong>{money(r.total)}</strong><span>{r.raw.toFixed(2)} lb × {money(l.price)} / lb</span><div><button className="secondary" onClick={()=>onEdit(l)}>Edit {l.cut}</button><button className="secondary" onClick={()=>onRemove(l.id)} aria-label={`Remove ${l.cut}`}>Remove</button></div></div></article>})}</div><button className="secondary" onClick={exportList}>Export dinner shopping list ↗</button></>:<p className="dinner-empty">Choose a meat, adjust the serving estimate, then add it to your dinner.</p>}</section>
}
