export const equipmentSources={
 drum:['Pit Barrel · model lighting instructions','https://pitbarrelcooker.com/pages/lighting-your-pbc'],
 pelletShutdown:['Traeger · shutdown by controller type','https://support.traeger.com/hc/en-us/articles/4407213153563-How-to-Shut-Down-Your-Traeger-Pellet-Grill'],
 safety:['NFPA · grilling safety','https://content.nfpa.org/-/media/project/storefront/catalog/files/safety-tip-sheets/grillingsafetytips.pdf?rev=820aae11c7284a8994c56d1285ae5c1a'],
 weber:['Weber · model manuals','https://www.weber.com/US/en/help/manuals/'],
 zones:['Weber · charcoal fire configurations','https://www.weber.com/US/en/grill-skills/mastering-charcoal/charcoal/fire-configurations/weber-34138.html'],
 wood:['Weber · wood forms & pairings','https://www.weber.com/US/en/blog/burning-questions/picking-the-perfect-wood-pairing/weber-29711.html'],
 pellets:['Traeger · hardwood pellet guide','https://www.traeger.com/learn/hardwood-pellet-guide'],
 pelletCare:['Traeger · food-quality pellets','https://support.traeger.com/hc/en-us/articles/4407213095451-Traeger-Pellets'],
 master:['Masterbuilt · product manuals','https://www.masterbuilt.com/pages/product-manuals'],
 cabinet:['Masterbuilt · fuel compatibility','https://www.masterbuilt.com/pages/faq/'],
 offset:['Oklahoma Joe’s · smoker owner’s manual','https://www.oklahomajoes.com/media/catalog/product/file/manual_pdf/x7s6oukpv41mwxlmudgg-0-15202029.pdf'],
 ceramic:['Big Green Egg · lighting & cooking guide','https://assets.biggreenegg.eu/app/uploads/2025/07/23104347/enjoy-6-hw-en.pdf'],
 griddle:['Blackstone · seasoning','https://blackstoneproducts.com/blogs/griddling-tips-tricks/griddle-seasoning-complete-guide'],
 griddleCare:['Blackstone · griddle care','https://blackstoneproducts.com/blogs/griddling-tips-tricks/how-to-take-care-of-your-griddle-complete-guide'],
 pizza:['Ooni · getting started','https://ooni.com/blogs/ooni-insights/things-you-should-know-to-get-your-pizza-oven-up-and-running'],
 food:['USDA · smoking meat and poultry','https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/smoking-meat-and-poultry']
};
export const cookers=[
 {id:'gas',name:'Gas grill',family:'Grills',fuel:'Propane / natural gas',effort:'Moderate',best:'Weeknight grilling, searing and indirect roasting.',control:'Burner settings control heat; leave a burner off for an indirect zone.',setup:['Check hoses, grease collection and the specified gas supply. Leak-test connections as the manual directs.','Light with the lid open using the exact model’s ignition procedure. Preheat with supervision.','Arrange a hot burner zone and an unlit cooler zone; verify grate-level temperature.'],shutdown:'Turn burners and the fuel supply off in the order specified by your manual. Cool before covering.',watch:'Never improvise a propane-to-natural-gas conversion.',source:'weber',diagram:'zones'},
 {id:'charcoal',name:'Charcoal kettle / barrel',family:'Grills',fuel:'Charcoal; optional wood chunks',effort:'Hands-on',best:'Searing, two-zone grilling and occasional smoking.',control:'Fuel layout sets the zones; intake and exhaust manage combustion.',setup:['Clear cold ash and open the airflow paths. Light charcoal with a rated starter on a noncombustible surface.','Bank lit coals on one side and leave the other side clear for indirect cooking.','Position food away from coals for slower cooking; change vents gradually while watching a grate probe.'],shutdown:'Close the vents if your model permits extinguishing this way. Wait until ash is completely cold before disposal.',watch:'Do not add lighter fluid to an established fire.',source:'zones',diagram:'zones'},
 {id:'kamado',name:'Ceramic / kamado',family:'Grills',fuel:'Manufacturer-approved charcoal',effort:'Moderate',best:'Heat retention, smoking, roasting and searing.',control:'Small vent adjustments matter; ceramic stores substantial heat.',setup:['Clear ash and load the approved charcoal. Use a suitable starter, never liquid accelerant.','Fit a heat deflector for indirect cooking before the cooker is hot.','Approach the target slowly. Follow the manual’s gradual lid-opening procedure to reduce flashback risk.'],shutdown:'Close the specified vents and allow the ceramic to cool naturally. Do not quench hot ceramic with water.',watch:'Overshooting is slow to correct; avoid treating vent positions as universal settings.',source:'ceramic',diagram:'indirect'},
 {id:'pellet',name:'Pellet grill / smoker',family:'Smokers',fuel:'Food-grade barbecue pellets',effort:'Controller-assisted',best:'Long cooks, roasting and repeatable setpoint control.',control:'The controller meters fuel and airflow; verify the actual cooking temperature.',setup:['Inspect a cold firepot, grease path and pellet supply according to the manual.','Keep pellets dry and use the prescribed startup sequence.','Choose a setpoint and stabilize before adding food; keep a separate food probe.'],shutdown:'Use the controller’s shutdown cycle. Do not cut power early unless the manual’s emergency instructions require it.',watch:'A flameout needs the maker’s recovery procedure; do not simply restart into accumulated fuel.',source:'pelletShutdown',diagram:'indirect'},
 {id:'offset',name:'Offset / stick burner',family:'Smokers',fuel:'Seasoned cooking-wood splits; coal bed',effort:'Hands-on',best:'Traditional barbecue and deliberate fire management.',control:'A small burning fire and an open flow path are more useful than smoldering a large fuel load.',setup:['Prepare the firebox and establish an appropriate coal bed.','Add manageable seasoned splits gradually; maintain combustion and the exhaust route.','Measure cooking-chamber heat near the food; account for the hotter firebox end.'],shutdown:'Follow the smoker’s extinguishing procedure. Handle ash only when fully cold.',watch:'Dense acrid smoke can signal poor combustion. Do not choke the fire just to lower temperature.',source:'offset',diagram:'offset'},
 {id:'water',name:'Vertical water smoker',family:'Smokers',fuel:'Charcoal & cooking-wood chunks',effort:'Moderate',best:'Ribs, shoulders and steady indirect cooking.',control:'Vent airflow, fuel quantity and an optional water pan affect heat behavior.',setup:['Arrange charcoal and wood as your model directs. Fit the heat barrier or water pan.','If using water, fill carefully before cooking; leave room for expansion and safe handling.','Stabilize with vents and check different rack temperatures; keep food above the intended indirect area.'],shutdown:'Close vents as permitted and cool fully before emptying ash or water.',watch:'A water pan supports heat management; it does not guarantee moist meat.',source:'weber',diagram:'indirect'},
 {id:'drum',name:'Drum / barrel smoker',family:'Smokers',fuel:'Charcoal & optional wood chunks',effort:'Moderate',best:'Hanging ribs and compact barbecue cooking.',control:'Intake settings and fuel basket position depend on the design.',setup:['Inspect the basket and air inlets. Use only the maker’s specified fuel and lighting amount.','Fit racks or rated hanging rods and hooks as instructed.','Maintain space between food, fire and walls; monitor food and chamber temperature.'],shutdown:'Follow the model’s vent closure and fuel-extinguishing procedure.',watch:'Secure hanging food; a dropped cut over fuel can cause a flare-up.',source:'drum',diagram:'indirect'},
 {id:'gravity',name:'Gravity-fed charcoal',family:'Smokers',fuel:'Approved lump / briquettes; permitted wood',effort:'Controller-assisted',best:'Charcoal cooking with powered temperature control.',control:'A fan regulates a charcoal fire; hopper seals and interlocks are part of the system.',setup:['Inspect seals, ash bin and grease handling while cold.','Fill and light using the model’s exact hopper, door and slide positions.','Use the controller to reach temperature; do not bypass lid or door switches.'],shutdown:'Follow the controller and shutdown-slide sequence in the exact model manual.',watch:'Keep required electrical power and safety interlocks intact during operation.',source:'master',diagram:'indirect'},
 {id:'electric',name:'Electric cabinet smoker',family:'Smokers',fuel:'Electric heat & approved smoking wood',effort:'Controller-assisted',best:'Controlled hot smoking in a compact cabinet.',control:'The element supplies heat; the approved chip tray supplies smoke.',setup:['Use an outdoor-rated installation and power supply exactly as specified.','Fit racks, drip tray and any required pan; load only the permitted wood form.','Preheat and use a food probe; leave ventilation in its prescribed configuration.'],shutdown:'Switch off, disconnect as directed, and clean only after cooling.',watch:'Pellets are not a universal substitute for chips. Indoor use is allowed only if the appliance is explicitly rated for it.',source:'cabinet',diagram:'indirect'},
 {id:'propane',name:'Propane cabinet smoker',family:'Smokers',fuel:'LP gas & approved chips / chunks',effort:'Moderate',best:'Hot smoking with independent burner heat.',control:'Burner heat and smoke-wood loading are separate controls.',setup:['Check gas connections and burner clearance; follow the leak test and ignition instructions.','Install wood and water pans only as the model directs.','Stabilize temperature and confirm burner operation throughout the cook.'],shutdown:'Shut off burner and cylinder as specified; cool before cleaning.',watch:'Do not convert to natural gas without explicit manufacturer approval.',source:'cabinet',diagram:'indirect'},
 {id:'griddle',name:'Flat-top / plancha',family:'Specialty',fuel:'Gas or electricity, model dependent',effort:'Moderate',best:'Smash burgers, vegetables, breakfast and small pieces.',control:'Surface temperature and separate burner zones determine browning.',setup:['On bare steel or cast iron, complete the maker’s seasoning procedure. Coated plates may need different care.','Preheat gradually and create hot and cooler surface zones.','Use a thin cooking-oil film and keep the grease channel clear; avoid crowding the surface.'],shutdown:'Turn heat off. Clean at the recommended surface temperature, dry and protect as the plate material requires.',watch:'Thick seasoning oil can leave sticky buildup. Do not apply bare-steel instructions to coated plates.',source:'griddle',diagram:'zones'},
 {id:'openfire',name:'Open-fire / adjustable grate',family:'Specialty',fuel:'Cooking wood / charcoal',effort:'Hands-on',best:'Live-fire grilling with adjustable radiant heat.',control:'Grate height, coal placement and distance from flame control exposure.',setup:['Use a purpose-built stable cooker where open fires are permitted.','Establish a controllable coal bed with clean, suitable fuel.','Start higher above the coals and lower gradually; maintain an escape zone for food.'],shutdown:'Use the approved extinguishing method and verify the fuel is cold before leaving.',watch:'Weather, local fire restrictions and spark management matter.',source:'safety',diagram:'zones'},
 {id:'hibachi',name:'Hibachi / konro',family:'Specialty',fuel:'Model-approved charcoal',effort:'Hands-on',best:'Skewers, small portions and concentrated direct heat.',control:'Fuel load and food distance matter; small cookers often have little indirect space.',setup:['Place outdoors on a stable heat-resistant support.','Use approved fuel and establish an even bed.','Cook in small batches, rotate food and have a separate holding area.'],shutdown:'Follow the cooker’s instructions; do not quench a hot ceramic body.',watch:'Charcoal produces carbon monoxide even when visible flames are gone.',source:'safety',diagram:'direct'},
 {id:'infrared',name:'Infrared / radiant grill',family:'Grills',fuel:'Gas or electric, model dependent',effort:'Moderate',best:'Fast surface browning and searing.',control:'A radiant emitter heats food; emitter care and preheat are design-specific.',setup:['Inspect and clean the emitter using the maker’s method.','Preheat as prescribed; avoid assuming ordinary gas-grill timing.','Watch closely and use a cooler finishing area when available.'],shutdown:'Follow the appliance’s burner or electrical shutdown procedure.',watch:'High surface heat does not prove the center of thick food is cooked.',source:'weber',diagram:'direct'},
 {id:'pizza',name:'Pizza / outdoor hearth oven',family:'Specialty',fuel:'Gas, wood, pellets or electric by model',effort:'Hands-on',best:'Pizza, bread and oven-safe pan cooking.',control:'Stone temperature and upper radiant heat are separate parts of the bake.',setup:['Fit only approved fuel hardware; place outdoors unless explicitly indoor-rated.','Preheat the stone and check it with an appropriate infrared thermometer.','Launch with a suitable peel and turn food as needed; use oven-rated cookware for other foods.'],shutdown:'Follow the model’s fuel shutdown sequence and let the stone cool naturally.',watch:'An infrared thermometer reads the surface, not food’s internal temperature.',source:'pizza',diagram:'oven'},
 {id:'contact',name:'Indoor contact grill',family:'Specialty',fuel:'Electricity',effort:'Moderate',best:'Small boneless portions in an indoor-rated appliance.',control:'Heated plates contact the food; thickness affects center doneness.',setup:['Verify the unit is indoor-rated and assemble its grease tray.','Preheat using the maker’s settings and avoid adding smoke fuel.','Choose even-thickness portions and check internal temperature separately.'],shutdown:'Switch off and unplug as directed; cool before removing plates.',watch:'An outdoor electric grill is not automatically an indoor appliance.',source:'weber',diagram:'direct'}
];
export const woods=[
 {id:'alder',name:'Alder',strength:1,profile:'Light and gentle',pairs:['Fish','Poultry','Vegetables'],why:'A starting point when you want smoke without overwhelming delicate food.',when:'Short, restrained smoke exposure on delicate ingredients.',tone:'#ba9a69',source:'wood'},
 {id:'apple',name:'Apple',strength:1,profile:'Mild, subtly fruity',pairs:['Pork','Poultry','Vegetables'],why:'Pairs naturally with lighter meats and sweet or fruit-forward glazes.',when:'Start gently; increase exposure to suit your recipe.',tone:'#bc7850',source:'pellets'},
 {id:'cherry',name:'Cherry',strength:2,profile:'Fruity and rounded',pairs:['Beef','Pork','Poultry','Lamb'],why:'A versatile smoke choice that can accompany a richer surface color.',when:'Useful alone or blended with oak or hickory for a stronger base.',tone:'#904d50',source:'pellets'},
 {id:'maple',name:'Maple',strength:1,profile:'Soft and mellow',pairs:['Pork','Poultry','Vegetables'],why:'A restrained choice for cooks where the seasoning should lead.',when:'Try lighter smoke loads on bacon-style flavors or poultry.',tone:'#c6a268',source:'pellets'},
 {id:'pecan',name:'Pecan',strength:2,profile:'Nutty, medium-bodied',pairs:['Pork','Poultry','Beef'],why:'Offers a fuller smoke profile without starting at the strongest end.',when:'A middle-ground option for roasts, ribs and mixed menus.',tone:'#aa805a',source:'wood'},
 {id:'oak',name:'Oak',strength:2,profile:'Balanced, robust',pairs:['Beef','Lamb','Game','Pork'],why:'A flexible foundation for richer cuts and hardwood blends.',when:'A useful baseline for longer barbecue cooks and comparing other woods.',tone:'#907653',source:'pellets'},
 {id:'hickory',name:'Hickory',strength:3,profile:'Strong and savory',pairs:['Pork','Beef','Game'],why:'Suits bold seasoning and substantial meat flavors.',when:'Start with less on delicate food; blend with a milder wood if needed.',tone:'#79624b',source:'wood'},
 {id:'mesquite',name:'Mesquite',strength:3,profile:'Intense and earthy',pairs:['Beef','Game'],why:'Adds a pronounced smoke character to strongly flavored food.',when:'Use sparingly for a first trial; short exposure or a mild blend gives more control.',tone:'#6f5648',source:'wood'}
];
export const methods=[
 ['Food preparation & safe endpoints','Thaw meat before low-temperature smoking and marinate in the refrigerator. USDA advises 145°F / 63°C plus a 3-minute rest for whole beef, pork, lamb and veal cuts; 160°F / 71°C for their ground meat; and 165°F / 74°C for poultry. Refrigerate leftovers within 2 hours; use species-specific guidance for game and fish.'],
 ['Two-zone cooking','Create a hot cooking zone and a cooler escape zone. Sear over heat, then move thick food away from direct heat to finish. A single-burner cooker may need a manufacturer-approved accessory instead.'],
 ['Direct vs indirect','Direct heat sits under the food for quick browning. Indirect heat cooks beside a fire or behind a deflector for larger pieces. Measure at food level; the lid thermometer may read differently.'],
 ['Reverse sear','Gently cook a thick cut with indirect heat, then finish with a brief sear. Monitor internal temperature and plan carryover; the sear is not a substitute for a safe cooking endpoint.'],
 ['Rotisserie','Use a model-compatible motor, spit and counterbalance. Center and secure the food, rotate by hand to check clearance before powering on, and manage drippings with the approved indirect setup.'],
 ['Water pans & drip pans','A water pan can buffer heat and add humidity. A drip pan catches fat. They are not interchangeable requirements; follow your cooker’s design and avoid putting a pan where it blocks airflow.'],
 ['Charcoal snake / staged fuel','On a compatible kettle, arranged fuel can extend a low-temperature cook. Layout, fuel and vent settings need a supervised trial; no arrangement guarantees a fixed cook duration.'],
 ['Hot smoking vs cold smoking','This guide covers hot cooking. Cold smoking needs a separate validated preservation process and temperature control; adding smoke alone does not make raw food safe.'],
 ['Probe placement & carryover','Keep the food probe in the thickest appropriate part, away from bone or large fat pockets. Place a grate probe near the food without touching metal. Verify unexpected readings with a second thermometer.'],
 ['Weather & fuel planning','Wind and cold change fuel use and stability. Plan a reserve, protect dry fuel and use only maker-approved weather accessories. Never enclose an outdoor cooker to solve a weather problem.']
];
export const troubleshooting=[
 ['Temperature keeps climbing','Move food to a cooler zone if needed. Check excessive fuel, wind and vent settings; reduce heat gradually. Ceramic and heavy steel react slowly.'],
 ['Bitter / acrid smoke','Check wood suitability, excessive smoke loading and poor airflow. Favor a stable burning fire; do not assume that more visible smoke means better flavor.'],
 ['Flare-ups / grease fire','Move food away from a small flare-up if safe. For a sustained fire, use the maker’s emergency procedure, keep people clear and call emergency services if needed. Never pour water onto a grease fire.'],
 ['Gas smell or failed ignition','Stop trying to ignite. Turn off gas if safe and follow the manual’s leak or failed-ignition procedure. Do not troubleshoot a suspected leak with a flame.'],
 ['Pellet flameout / power failure','Follow the model’s restart procedure; accumulated fuel may need removal after cooling. Assess the food’s time and temperature separately before continuing.'],
 ['Uneven cooking','Check probe position, known hot spots, crowding and blocked airflow. Rotate food if appropriate rather than trusting a single lid reading.'],
 ['Sticky or rusty griddle','Review oil quantity, cleaning, drying and storage. Use plate-material-specific care; nonstick coatings and bare steel require different treatment.']
];
