import React,{useState} from 'react';
const localDate=()=>{const d=new Date(Date.now()+7200000);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const cutDraft=()=>{try{return JSON.parse(localStorage.getItem('omapit-cut-draft')||'null')}catch{return null}};
const newFood=()=>({name:'',category:'quick',target:165,pit:350,minutes:30,prep:10,rest:10,hold:0,slots:1,resource:'main',device:'',alarm:true});
export function GuidedSetup({data,act,busy,onBack}){
 const [draft,setDraft]=useState(cutDraft);

 const [step,setStep]=useState(0),[name,setName]=useState('Sunday dinner'),[date,setDate]=useState(localDate),[capacity,setCapacity]=useState(2),[grill,setGrill]=useState('Main grill'),[preheat,setPreheat]=useState(15),[foods,setFoods]=useState(()=>[{...newFood(),name:draft?.name||'',category:draft?.category||'quick',target:data.unit==='C'?74:165,pit:data.unit==='C'?177:350}]);
 const change=(i,k,v)=>setFoods(list=>list.map((f,n)=>n===i?{...f,[k]:v}:f));
 const submit=e=>{e.preventDefault();if(step<2){setStep(step+1);return}act('guided_setup',{name,serve_at:new Date(date).toISOString(),unit:data.unit,preheat,resources:[{id:'main',name:grill,capacity}],foods},'Meal and plan created').then(ok=>{if(ok){localStorage.removeItem('omapit-cut-draft');setDraft(null)}})};
 return <section className="feature-screen setup-screen"><p className="eyebrow">FROM FIRST SPARK TO THE TABLE</p><h1>Build a meal that comes together.</h1><div className="setup-progress">{['The table','The food','Review & light up'].map((v,i)=><span key={v} className={step===i?'current':''}>{i+1}. {v}</span>)}</div>{draft&&<p className="info">Meal draft: {draft.name} · {draft.weight} {draft.weightUnit}. Weight is a planning note; timing and temperatures remain your choices. <button className="text-button" onClick={()=>{localStorage.removeItem('omapit-cut-draft');setDraft(null)}}>Clear saved cut</button></p>}{data.active?<article className="feature-card"><h2>You already have a cook underway.</h2><p className="muted">Keep it in Meal, or finish and save it before starting a new guided meal. Your current journal will stay intact.</p><button className="secondary" onClick={onBack}>Back to current cook</button></article>:<form className="feature-form" onSubmit={submit}>
 {step===0&&<article className="feature-card"><h2>When are we eating?</h2><label>Meal name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><label>Serving date and time<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} required/></label><div className="form-pair"><label>Grill or cooking zone<input value={grill} onChange={e=>setGrill(e.target.value)} required maxLength={100}/></label><label>Available space units<input type="number" value={capacity} onChange={e=>setCapacity(Number(e.target.value))} min="1" max="20" required/></label></div><label>Preheat estimate (minutes)<input type="number" min="0" max="180" value={preheat} onChange={e=>setPreheat(e.target.value)} required/></label><p className="muted small">Define a space unit as a pan, rack or portion of your grate. You decide how much each food needs.</p></article>}
 {step===1&&<div className="food-stack">{foods.map((f,i)=><article className="feature-card" key={i}><div className="panel-heading"><h2>Food {i+1}</h2>{foods.length>1&&<button type="button" className="text-button" onClick={()=>setFoods(foods.filter((_,n)=>n!==i))}>Remove food {i+1}</button>}</div><label>Food {i+1} name<input value={f.name} onChange={e=>change(i,'name',e.target.value)} placeholder={i?'Corn on the cob':'Chicken thighs'} required maxLength={100}/></label><div className="form-pair"><label>Workflow<select value={f.category} onChange={e=>change(i,'category',e.target.value)}>{['quick','poultry','vegetables','smoke','manual'].map(v=><option key={v}>{v}</option>)}</select></label><label>Probe<select value={f.device} onChange={e=>change(i,'device',e.target.value)}><option value="">Manual readings</option>{data.devices.filter(d=>['ble','bridge'].includes(d.source)&&!d.error).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><div className="form-pair">{[['target',`Your food target (°${data.unit})`],['pit',`Cooking temperature (°${data.unit})`],['slots','Space units used'],['minutes','Cook estimate (minutes)'],['prep','Prep minutes'],['rest','Rest minutes'],['hold','Planned hold minutes']].map(([k,l])=><label key={k}>{l}<input type="number" value={f[k]} onChange={e=>change(i,k,e.target.value)} required step={['pit','target'].includes(k)?'0.1':'1'} min={k==='slots'||k==='minutes'?1:['pit','target'].includes(k)?-40:0} max={k==='slots'?capacity:['pit','target'].includes(k)?1000:1440}/></label>)}</div><label className="checkbox-label"><input type="checkbox" checked={f.alarm} onChange={e=>change(i,'alarm',e.target.checked)}/>Create a target reminder</label><p className="muted small">Targets and hold conditions are your choices. Confirm safe cooking and holding independently.</p></article>)}<button type="button" className="secondary" disabled={foods.length>=8} onClick={()=>setFoods([...foods,{...newFood(),target:data.unit==='C'?74:165,pit:data.unit==='C'?177:350}])}>Add another food</button></div>}
 {step===2&&<article className="feature-card setup-review"><p className="eyebrow">YOUR MEAL AT A GLANCE</p><h2>{name}</h2><p>{new Date(date).toLocaleString()} · {grill} · {capacity} space units</p>{foods.map((f,i)=><div className="list-line" key={i}><span><strong>{f.name}</strong><small>{f.prep}m prep → {f.minutes}m cook → {f.rest}m rest{Number(f.hold)>0?` → ${f.hold}m hold`:''}</small></span><span>{f.pit}°{data.unit}<small>{f.slots} space units · {f.device?'Mapped probe':'Manual'}</small></span></div>)}<p className="muted">We’ll reserve {preheat} minutes for preheating, separate incompatible cooking temperatures, and work backward from the table time. Review the timeline before cooking.</p></article>}
 <div className="button-row"><button type="button" className="secondary" onClick={()=>step?setStep(step-1):onBack()}>{step?'Back':'Cancel'}</button><button className="primary" disabled={busy}>{step===2?'Create meal & plan':'Continue'}</button></div></form>}</section>
}
