import React,{useRef,useState,useEffect} from 'react';
import './hunter-visual.css';
const order=['prepare','dress','skin','cool','breakdown','store'];
const text={
 prepare:{title:'Know the kit before you leave',look:'Identify clean tools, protective equipment, bags, labels and cooling supplies before handling an animal.',terms:[['Harvest identity','The record that keeps one animal’s meat traceable through transport, testing and packaging.'],['Cold chain','Keeping meat chilled through handling, transport and storage.']],cue:'Prepare cooling capacity before the hunt. A cooler is useful only if it can actually hold the required temperature.'},
 dress:{title:'Orient yourself before making a cut',look:'The animal is shown on its back. This is an external orientation image: it does not show the organs or a safe incision depth.',terms:[['Field dressing / evisceration','Removing the internal organs after harvest while protecting edible meat from contamination.'],['Abdomen','The body area containing the digestive organs. Puncturing them can contaminate meat.']],cue:'Watch a species-appropriate demonstration and have an experienced person guide your first attempt. The picture is not a cut map.'},
 skin:{title:'Separate the outer covering from clean meat',look:'Keep the dirty outer covering away from exposed muscle. Pull gently to expose attachments; do not cut blindly into meat.',terms:[['Hide','The skin and hair covering a large animal.'],['Connective tissue','The thin attachments between layers. Work at those attachments rather than removing chunks of muscle.']],cue:'Change dirty gloves or clean hands before touching clean meat. Hide, hair and feathers belong away from the processing area.'},
 cool:{title:'Keep meat above meltwater',look:'Separated packages sit above sealed cooling packs. The image illustrates arrangement, not a measured temperature or proof that the meat is cold.',terms:[['Game bag','A clean breathable bag that protects exposed meat during initial handling. It is not freezer packaging.'],['Temperature check','Use a thermometer to verify chilled storage and transport at or below 40°F / 4°C.']],cue:'Do not seal warm meat in plastic. Begin cooling promptly and verify the meat and cooler conditions.'},
 breakdown:{title:'Recognize the portions',look:'Separated portions make the anatomy easier to understand. This is the result of breakdown, not an instruction to saw through the spine.',terms:[['Quarter','A front shoulder/leg or rear leg portion from a large animal.'],['Deboning','Removing meat from bones with controlled cuts along the actual anatomy.']],cue:'Keep whole-muscle cuts and grind trim separate. Inspect damaged areas; use an experienced processor when condition or anatomy is uncertain.'},
 store:{title:'Package one meal at a time',look:'Cold portions are sealed in freezer-rated packaging. Add the actual species, cut, weight, date, animal identity and any testing status to each label.',terms:[['Freezer burn','Moisture loss that damages quality; good freezer packaging limits exposure to air.'],['Vacuum sealing','Removing air from a package. It does not make raw meat safe at room temperature.']],cue:'Freeze at 0°F / −18°C or below. Keep test-pending meat identifiable and follow the applicable wildlife guidance.'}
};
const speciesText={deer:{name:'Deer',example:'A deer is illustrated. Elk share broad preparation concepts but differ in size and handling needs.'},hog:{name:'Wild hog',example:'A feral hog is illustrated. Species-specific disease precautions and processor guidance still apply.'},birds:{name:'Game bird',example:'A pheasant is illustrated. Duck, goose, turkey and other birds require species-appropriate guidance.'}};
export function hunterPhotoStyle(species,stage){const tile=order.indexOf(stage),row=Math.floor(tile/2),right=tile%2;const x=right?(species==='deer'?515:516):0,w=right?(species==='deer'?509:508):508;const bounds=species==='deer'?[[0,503],[510,485],[1001,535]]:species==='hog'?[[0,503],[510,481],[997,539]]:[[0,506],[513,481],[1001,535]];const [y,h]=bounds[row];return {backgroundImage:`url('/assets/guides/hunter-${species}.jpg')`,backgroundSize:`${1024/w*100}% ${1536/h*100}%`,backgroundPosition:`${x/(1024-w)*100}% ${y/(1536-h)*100}%`,aspectRatio:`${w}/${h}`};}
export function HunterVisual({species,stage}){
 const [labels,setLabels]=useState(true),[expanded,setExpanded]=useState(false);const ref=useRef(null);useEffect(()=>{if(expanded)ref.current?.showModal()},[expanded]);
 const d={...text[stage]},s=speciesText[species],tile=order.indexOf(stage);let points=[];
 if(stage==='dress')points=species==='birds'?[[50,38,'Breast'],[26,43,'Wing'],[32,65,'Leg / thigh']]:[[50,36,'Chest'],[50,53,'Abdomen'],[50,73,'Hindquarters']];
 if(stage==='skin')points=species==='birds'?[[25,48,'Skin on'],[60,48,'Skin off']]:[[29,48,'Hide side'],[72,48,'Clean muscle']];
 if(species==='birds'&&stage==='cool')d.terms=[['Chilled packaging','Clean food-safe packaging used after initial cooling, separate from dirty feathers and field surfaces.'],['Temperature check','Verify chilled storage and transport at or below 40°F / 4°C with a thermometer.']];
 if(species==='birds'&&stage==='skin'){d.title='Skin off or pluck: two different finishes';d.look='The plucked bird retains its skin. The skinned bird loses feathers with the skin. Keep the removed covering away from the clean portions.';d.terms=[['Plucking','Removing feathers while leaving skin attached.'],['Skinning a bird','Removing the skin and feathers together.']];}
 if(species==='birds'&&stage==='breakdown'){d.terms=[['Breast meat','The paired muscles alongside the breastbone.'],['Leg and thigh','A separate portion that can need a different cooking approach from breast meat.']];d.look='Breasts, leg-and-thigh portions and wings are shown separately. Locate real joints before separating pieces; do not force a knife through hard bone.';}
 if(species==='deer'&&stage==='breakdown')d.terms=[['Backstrap','The long muscle along the outside of each side of the spine.'],['Tenderloin','A smaller muscle inside the body cavity near the rear of the spine; it is not the backstrap.']];
 const content=<><div className="hunter-visual-toolbar"><span>SEE THE STEP / {s.name.toUpperCase()}</span><div>{points.length>0&&<button aria-pressed={labels} onClick={()=>setLabels(!labels)}>{labels?'Hide':'Show'} labels</button>}<button onClick={()=>setExpanded(!expanded)}>{expanded?'Close':'Enlarge image'}</button></div></div><div className="hunter-photo" role="img" aria-label={`${s.name}: ${d.title}. ${d.look}`} style={hunterPhotoStyle(species,stage)}>{labels&&points.length>0&&<svg viewBox="0 0 100 100" aria-hidden="true">{points.map(([x,y,name],i)=><g key={name}><circle cx={x} cy={y} r="3" fill="#101923" stroke="#ffe1a6" strokeWidth=".5"/><text x={x} y={y+1.2} textAnchor="middle" fontSize="3.8" fill="#fff2d9">{i+1}</text></g>)}</svg>}</div><div className="hunter-photo-title"><span>0{tile+1} / FIELD TO FREEZER</span><strong>{d.title}</strong></div>{points.length>0&&<div className="hunter-anatomy-key">{points.map(([x,y,name],i)=><span key={name}><b>{i+1}</b>{name}</span>)}</div>}<div className="hunter-look"><h3>What you’re looking at</h3><p>{d.look}</p><small>{s.example}</small></div><dl className="hunter-glossary">{d.terms.map(([term,definition])=><div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl><div className="hunter-visual-cue"><strong>BEFORE YOU CONTINUE</strong><p>{d.cue}</p></div><small className="hunter-illustration-note">Realistic generated learning illustration. Anatomy and staging are illustrative; use the linked demonstration for the actual procedure.</small></>;
 return <section className="hunter-visual">{expanded?<dialog ref={ref} className="hunter-visual-dialog" aria-label="Enlarged hunter preparation image" onClose={()=>setExpanded(false)}>{content}</dialog>:content}</section>;
}
