import {ThemeSettings} from './ThemeSettings';
import React,{useState} from 'react';
import {CheckCircle} from '@phosphor-icons/react/dist/csr/CheckCircle';
import './logo-settings.css';
import {PixelWordmark} from './PixelWordmark';
import {HeaderFire} from './HeaderFire';
import {CommunitySettings} from './CommunitySettings';

export const logoOptions=[

 {id:'meat',name:'Meat',src:'/assets/wordmarks/meat.png',description:'Seared bark, rich meat grain and a warm ember accent.',default:true},
 {id:'equipment',name:'BBQ equipment',src:'/assets/wordmarks/equipment.png',description:'Cast iron, brushed steel, copper rivets and walnut handles.'},
 {id:'charcoal',name:'Burning charcoal',src:'/assets/wordmarks/charcoal.png',description:'Glowing hardwood charcoal, ash, flame and smoke.'},
 {id:'pixel',name:'Animated pixel art',description:'Hand-drawn copper and charcoal lettering, glowing coals, flickering flame and drifting sparks.'},
];
export function readLogoPreference(){try{const saved=localStorage.getItem('omapit-logo-v1');return logoOptions.some(option=>option.id===saved)?saved:'meat'}catch{return 'meat'}}

export function LogoSettings({value,onChange,error,headerAnimation,onHeaderAnimation,motion=true,onMotion,theme,onTheme}){
 const [section,setSection]=useState('wordmark');
 const sectionKeys=e=>{const ids=['wordmark','themes','animation','community'];const i=ids.indexOf(section);let next;if(e.key==='ArrowRight')next=(i+1)%ids.length;else if(e.key==='ArrowLeft')next=(i+ids.length-1)%ids.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=ids.length-1;else return;e.preventDefault();setSection(ids[next]);e.currentTarget.parentElement.querySelectorAll('[role=tab]')[next].focus();};
 return <section className="logo-settings"><p className="eyebrow">MAKE IT YOURS</p><h1>Settings</h1><p className="muted">A little character for your cooking companion.</p><div className="settings-tabs" role="tablist" aria-label="Settings sections">{[['wordmark','Wordmark'],['themes','Themes'],['animation','Header & motion'],['community','Community & agents']].map(([id,label])=><button key={id} role="tab" id={'settings-tab-'+id} aria-selected={section===id} aria-controls={'settings-panel-'+id} tabIndex={section===id?0:-1} onKeyDown={sectionKeys} onClick={()=>setSection(id)}>{label}</button>)}</div>{section==='wordmark'&&<div role="tabpanel" id="settings-panel-wordmark" aria-labelledby="settings-tab-wordmark"><div className="logo-setting-heading"><div><h2>Your OmaPit wordmark</h2><p>Choose the material that feels like your fire.</p></div><span>Appearance</span></div><div className="logo-choice-grid" role="group" aria-label="OmaPit logo">
 {logoOptions.map(option=><button key={option.id} className={'logo-choice '+(value===option.id?'selected':'')} aria-label={option.name+' logo'} aria-pressed={value===option.id} onClick={()=>onChange(option.id)}><div className="logo-choice-preview">{option.id==='pixel'?<PixelWordmark animate={motion}/>:<img src={option.src} alt=""/>}</div><div className="logo-choice-copy"><div><h3>{option.name}</h3>{option.default&&<span className="logo-default">Default</span>}</div><p>{option.description}</p><span className="logo-choice-state">{value===option.id?<><CheckCircle size={18} weight="fill" aria-hidden="true"/>Selected</>:'Use this logo'}</span></div></button>)}
 </div><p className="logo-storage-note" role="status">{error||`Selected: ${logoOptions.find(option=>option.id===value)?.name}. Your choice is saved automatically on this browser.`}</p></div>}{section==='themes'&&<div role="tabpanel" id="settings-panel-themes" aria-labelledby="settings-tab-themes"><ThemeSettings value={theme} onChange={onTheme} error={error}/></div>}{section==='animation'&&<div role="tabpanel" id="settings-panel-animation" aria-labelledby="settings-tab-animation"><label className="settings-motion"><span><strong>Animate the app</strong><small>Header scenes, the logo, grill effects and sauce pour. Your system’s reduced-motion preference still applies.</small></span><input type="checkbox" checked={motion} onChange={onMotion} aria-label="Animate the app"/></label><div className="logo-setting-heading"><div><h2>Header animation</h2><p>Detailed pixel art, a little motion, your kind of barbecue.</p></div><span>Appearance</span></div><div className="header-animation-choices" role="group" aria-label="Header animation">{[['fire','Pixel fire','Flame tongues, smoke and glowing sparks.','🔥'],['meats','Falling meats','Marbled steaks, rib racks, drumsticks and sausages.','🥩'],['utensils','Falling utensils','Steel spatulas, tongs, carving forks and basting brushes.','🍴'],['kitchen','Professional kitchen','Chefs at the line, steaming pans, plated food and a polished steel pass.','👨‍🍳'],['smoke','Smoke only','Cool, softly rolling smoke. No flames or embers.','☁️'],['backyard','Backyard BBQ','An evening cookout with grill cooks, guests and glowing string lights.','🏡']].map(([id,name,description,icon])=><button className={headerAnimation===id?'selected':''} key={id} aria-pressed={headerAnimation===id} onClick={()=>onHeaderAnimation(id)}><div className="animation-choice-preview"><HeaderFire animate={false} variant={id}/></div><h3>{name}</h3><p>{description}</p><b>{headerAnimation===id?'Selected':'Use animation'}</b></button>)}</div><p className="logo-storage-note">Saved automatically on this browser. Animations respect reduced motion and your existing motion setting.</p></div>}{section==='community'&&<div role="tabpanel" id="settings-panel-community" aria-labelledby="settings-tab-community"><CommunitySettings/></div>}</section>
}
