import {extraRubIngredients,extraRubs} from './rubExpansion.js';
const weber='https://www.weber.com/US/en/blog/tips-techniques/top-tips-for-grilling-vegetables/weber-48939.html';
const breadSource='https://contact-emea.weber.com/hc/en-ie/articles/360000623338-Stand-up-Kettle-Cooking-Methods';
const tx='https://franklinbbq.com/menu/';
const kc='https://www.joeskc.com/pages/restaurant-menu';
const nc='https://www.visitnc.com/list/taste-north-carolina-barbecue-styles-history-new-twists';
const mem='https://hogsfly.com/restaurant-menu/';
const item=(id,name,family,profile,prep,zone,ready,portion,unit,lead,pairs,allergens='',source=weber)=>({id,name,family,profile,prep,zone,ready,portion,unit,lead,pairs,allergens,source});
export const foodLibraries={
 veggies:{title:'Let the garden meet the fire.',subtitle:'A little char. A lot of color. Make vegetables part of the main event.',label:'Veggie Explorer',noun:'vegetable',items:[
 item('corn','Sweet corn','Sturdy','Sweet, smoky & juicy','Remove husks and silk. Brush lightly with oil; turn as each side colors.','Direct medium','Kernels tender with scattered char; do not wait for every kernel to blacken.',1,'ears','Prep before the main cook; grill near serving.',['Pork ribs','Chili-lime rub']),
 item('zucchini','Zucchini','Quick','Tender, bright & lightly charred','Slice lengthwise into thick planks. Dry, lightly oil and place across the grates.','Direct medium-high','Marked on both sides, tender with a little resistance.',150,'g','Cut ahead; season just before grilling.',['Chicken','Herb rub']),
 item('asparagus','Asparagus','Quick','Green, nutty & crisp-tender','Trim woody ends. Oil lightly; arrange across grates or use a basket.','Direct medium','Tender stems with crisp tips; thin spears finish first.',120,'g','Wash and dry ahead; finish while meat rests.',['Lamb','Lemon-herb']),
 item('peppers','Bell peppers','Quick','Sweet, silky & smoky','Remove seeds and core. Cut into broad panels; lightly oil both sides.','Direct medium','Softened flesh and browned skin; peel only if desired.',150,'g','Prep ahead; turn and remove pieces individually.',['Sausages','Flatbread']),
 item('mushrooms','Mushrooms','Quick','Savory, juicy & earthy','Clean and dry. Use large caps on the grate; put small mushrooms in a basket.','Direct medium','Tender and juicy, browned outside; avoid drying them out.',150,'g','Clean before the cook; oil just before grilling.',['Steak','Pepper rub']),
 item('eggplant','Eggplant','Sturdy','Velvety inside, smoky outside','Cut thick rounds or planks. Brush both sides with oil; avoid thin fragile slices.','Direct medium, then cooler zone','Fully soft through the center, with no firm spongy layer.',150,'g','Cut near cooking; allow extra cooler-zone space.',['Lamb','Yogurt dressing']),
 item('onions','Sweet onions','Sturdy','Caramelized, sweet & fragrant','Cut thick rounds or root-attached wedges. Use skewers or a basket to hold layers.','Direct medium, then cooler zone','Layers tender and edges caramelized; move away from flare-ups.',100,'g','Cut before the cook; keep wedges together.',['Brisket','Burgers']),
 item('potato','Potatoes','Slow','Crisp edges & fluffy centers','Parboil wedges until almost tender, drain and dry. Oil before finishing on the grill.','Direct finish after parboiling','Center soft and outside crisp; charring alone does not mean cooked.',200,'g','Parboil before the main cook; finish near serving.',['Pork','Garlic-pepper']),
 item('cauliflower','Cauliflower','Sturdy','Roasty, nutty & substantial','Cut thick center steaks; keep loose florets in a basket. Lightly oil.','Indirect to tender, direct finish','Stem pierced easily and surface browned.',180,'g','Prep ahead; give thick stems a head start.',['Mustard sauce','Smoky rub']),
 item('cabbage','Cabbage wedges','Sturdy','Sweet core & crisp charred edges','Cut wedges through the core so leaves hold together. Brush cut faces with oil.','Direct medium, then cooler zone','Core tender and leaves browned, not burnt through.',180,'g','Prep ahead; keep core intact until serving.',['Pulled pork','Vinegar sauce'])]},
 bread:{title:'The best bite needs good bread.',subtitle:'Toast, tear, soak up the sauce. Find the right bread for your barbecue.',label:'Bread Explorer',noun:'bread',items:[
 item('texas-toast','Texas toast','Toast','Golden, buttery & sturdy','Use thick prepared bread. Spread a thin layer of softened butter or oil on each face.','Direct medium; watch continuously','Golden faces with a warm center. Buttered bread can flare.',2,'slices','Toast last and serve immediately.',['Brisket','Beans'],'Wheat; dairy if buttered',breadSource),
 item('sourdough','Rustic sourdough','Toast','Crisp crust & tangy crumb','Cut thick slices; brush lightly with oil. Rub with cut garlic after toasting if desired.','Direct medium','Light char, crisp edges and a soft middle.',2,'slices','Slice ahead; toast while the meat rests.',['Steak','Grilled vegetables'],'Wheat',breadSource),
 item('flatbread','Flatbread','Toast','Soft, smoky & made for sharing','Warm prepared flatbreads briefly; brush lightly with oil. Keep stacked in a clean towel.','Direct medium; brief turns','Pliable and warm with light char; remove before brittle.',1,'pieces','Warm just before serving.',['Lamb','Eggplant'],'Wheat; check recipe for dairy',breadSource),
 item('buns','Sandwich buns','Toast','Soft center & a toasted face','Split prepared buns and lightly butter or oil the cut sides. Keep away from high flame.','Direct medium, cut face down','Cut face golden while the outside stays soft.',1,'buns','Toast after patties or pork come off the grill.',['Burgers','Pulled pork'],'Wheat; may contain egg, dairy, sesame',breadSource),
 item('cornbread','Skillet cornbread','Bake','Golden, crumbly & comforting','Use your tested cornbread batter in a greased oven-safe skillet. Follow its baking temperature and recipe.','Indirect heat, covered grill','Follow recipe doneness cues; browned edges and a set center.',1,'wedges','Bake before service; allow a short cooling period.',['Chili','Pork shoulder'],'Often egg and dairy; may contain wheat',breadSource),
 item('garlic-bread','Garlic bread','Toast','Buttery, fragrant & crisp','Spread prepared bread with a modest layer of garlic butter; warm indirectly before a brief toast.','Indirect warm, direct finish','Butter melted, center warm and edges golden.',2,'slices','Prepare ahead; finish immediately before serving.',['Chicken','Tomato salad'],'Wheat, dairy if buttered',breadSource)]},
 sides:{title:'Every region brings something.',subtitle:'Build a plate with contrast: something rich, something fresh, something to share.',label:'Regional Sides Explorer',noun:'side',items:[
 item('pinto','Pinto beans','Texas','Savory, hearty & peppery','Start with fully cooked beans. Warm with onion, garlic and stock; finish with pepper to taste.','Covered pot or indirect oven-safe pan','Hot throughout with a spoonable consistency; add liquid as needed.',150,'g','Make ahead; reheat before serving.',['Brisket','Texas toast'],'Check stock and added meat',tx),
 item('potato-salad','Potato salad','Texas','Cool, creamy & tangy','Cook diced potatoes until tender, cool, then fold into your preferred dressing. Keep refrigerated.','Off the grill · chilled','Tender intact potatoes and well-balanced dressing.',150,'g','Make earlier and refrigerate; set out in small batches.',['Brisket','Smoked sausage'],'May contain egg, dairy or mustard',tx),
 item('bbq-beans','Barbecue beans','Kansas City','Sweet-savory & smoky','Start with cooked beans. Add a little barbecue sauce and onion; warm until flavors meld.','Indirect oven-safe pan','Hot, slightly thickened sauce; keep from drying at the edges.',150,'g','Prepare ahead; warm during the main cook.',['Ribs','Burnt ends'],'Check sauce and added meat',kc),
 item('creamy-slaw','Creamy coleslaw','Kansas City','Cool, crunchy & mellow','Shred cabbage and carrot. Dress lightly near serving; refrigerate until needed.','Off the grill · chilled','Crisp leaves with a light coating, not a pool of dressing.',100,'g','Shred ahead; dress close to service.',['Pulled pork','Ribs'],'Often egg; may contain dairy or mustard',kc),
 item('red-slaw','Piedmont red slaw','North Carolina','Bright, crisp & tomato-vinegar tang','Finely chop cabbage. Make a light tomato-vinegar dressing; adjust sweetness and pepper to taste.','Off the grill · chilled','Crunchy cabbage and balanced tang; avoid overdressing.',100,'g','Chop ahead; chill before serving.',['Pork shoulder','Hushpuppies'],'Check dressing ingredients',nc),
 item('hushpuppies','Hushpuppies','North Carolina','Golden, crisp & tender','Use a tested cornmeal batter and controlled fryer setup. This is a stovetop companion, not a grill recipe.','Off the grill · fryer','Cook through following your recipe; drain well and serve hot.',3,'pieces','Mix per recipe; fry close to service.',['Chopped pork','Slaw'],'Often wheat, egg and dairy',nc),
 item('memphis-slaw','Mustardy slaw','Memphis','Crunchy, tangy & mustard-forward','Toss finely shredded cabbage with a light mustard-vinegar dressing; season to taste.','Off the grill · chilled','Crisp texture and sharpness to balance rich pork.',100,'g','Prepare before the cook; refrigerate until serving.',['Dry-rub ribs','Pork shoulder'],'Mustard; check dressing',mem),
 item('memphis-beans','Smoky beans','Memphis','Rich, smoky & gently sweet','Warm cooked beans with your preferred barbecue seasoning and sauce. Keep enough liquid for a spoonable side.','Indirect covered pan','Hot throughout and thick enough to coat the beans.',150,'g','Make ahead; reheat during the cook.',['Dry-rub ribs','Slaw'],'Check sauce and stock',mem)]}
};
export const rubIngredients={...extraRubIngredients,salt:'Fine salt',pepper:'Coarse black pepper',paprika:'Smoked paprika',sugar:'Brown sugar',garlic:'Granulated garlic',onion:'Onion powder',mustard:'Mustard powder',cayenne:'Cayenne',cumin:'Ground cumin',rosemary:'Dried rosemary',thyme:'Dried thyme',coriander:'Ground coriander'};
export const rubs=[
 {id:'pepper',name:'Pepper & smoke',family:'Savory',profile:'Bold pepper. Clean bark. No added sugar.',pairs:['Beef','Brisket','Mushrooms'],recipe:{salt:25,pepper:45,garlic:20,onion:10},tip:'A pepper-forward starting blend. Use a thin even coat; more seasoning is not always better.'},
 {id:'sweet',name:'Sweet red bark',family:'Sweet',profile:'Paprika warmth with a caramel edge.',pairs:['Pork','Ribs','Chicken'],recipe:{salt:15,paprika:30,sugar:30,pepper:10,garlic:10,mustard:5},tip:'Best suited to gentle, indirect cooking. Sugar can scorch over strong direct heat.'},
 {id:'chili',name:'Smoky chili',family:'Spicy',profile:'Earthy cumin and a restrained kick.',pairs:['Pork','Chicken','Corn'],recipe:{salt:20,paprika:30,cumin:15,pepper:10,garlic:15,cayenne:5,onion:5},tip:'Test a pinch on a small cooked sample. Reduce cayenne before scaling up.'},
 {id:'herb',name:'Garden & garlic',family:'Herby',profile:'Fragrant herbs, garlic and black pepper.',pairs:['Lamb','Goat','Potatoes'],recipe:{salt:20,garlic:30,pepper:15,rosemary:15,thyme:10,coriander:10},tip:'Crush dried herbs for an even coat. Fresh herbs change the storage and application method.'},
 {id:'saltfree',name:'Smoke without salt',family:'Salt-free',profile:'Aromatic spice for food salted separately.',pairs:['Beef','Vegetables','Dry-brined meat'],recipe:{paprika:35,pepper:25,garlic:20,onion:10,cumin:10},tip:'Useful when the food is already salted. Check packaged spices for added salt.'},
 {id:'mustard',name:'Mustard & pepper',family:'Savory',profile:'A tangy aroma and rounded pepper warmth.',pairs:['Pork','Chicken','Cabbage'],recipe:{salt:20,mustard:25,pepper:20,paprika:15,garlic:15,sugar:5},tip:'Mustard is an allergen in some jurisdictions. Check guests’ needs and every ingredient label.'}
 ,...extraRubs
];
export function portionTotal(guests,portion,reserve=0){const a=Number(guests),b=Number(portion),c=Number(reserve);return guests!==''&&portion!==''&&reserve!==''&&Number.isInteger(a)&&a>=1&&a<=200&&Number.isFinite(b)&&b>0&&b<=2000&&Number.isFinite(c)&&c>=0&&c<=100?Math.round(a*b*(1+c/100)*1e6)/1e6:null;}
export function rubBatch(weight,unit,rate,recipe){const w=Number(weight),r=Number(rate);if(weight===''||rate===''||!Number.isFinite(w)||w<=0||w>1000||!['lb','kg'].includes(unit)||!Number.isFinite(r)||r<=0||r>100)return null;const entries=Object.entries(recipe);if(!entries.length||entries.some(([id,v])=>!rubIngredients[id]||v===''||!Number.isFinite(Number(v))||v<0||v>100))return null;const sum=entries.reduce((a,[,v])=>a+Number(v),0);if(sum<=0)return null;const kg=w*(unit==='lb'?0.45359237:1),grams=kg*r;return {kg,grams,ingredients:entries.map(([id,v])=>({id,grams:grams*Number(v)/sum,percent:100*Number(v)/sum})),saltGrams:grams*Number(recipe.salt||0)/sum,sugarGrams:grams*Number(recipe.sugar||0)/sum};}
