import React from 'react';
import {CookingPot} from '@phosphor-icons/react/dist/csr/CookingPot';
import {ArrowRight} from '@phosphor-icons/react/dist/csr/ArrowRight';
const when=t=>new Date(t*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
export function NextAction({data,act,busy,online=true,onNavigate,compact=false}){
 const now=Date.now()/1000;const alarm=data.alarm_episodes.find(e=>!e.resolved&&!e.acknowledged&&e.snoozed_until<=now);
 const stale=data.foods.find(f=>!f.finished&&f.reading&&!f.reading.fresh);
 const tasks=data.plan.tasks.filter(t=>!t.completed);const running=tasks.filter(t=>t.started).sort((a,b)=>a.earliest_finish-b.earliest_finish)[0];
 const ready=tasks.filter(t=>!t.started&&t.ready).sort((a,b)=>a.planned_start-b.planned_start)[0];
 const task=running?.estimate_elapsed?running:running&&(!ready||ready.planned_start>now)?running:ready||running;
 const isRunning=task?.started;const due=task&&task.planned_start<=now;
 if(online&&data.active?.source==='demo')return <article className={'sample-cook-banner '+(compact?'compact':'')} aria-label="Sample cook introduction"><div className="sample-cook-icon"><CookingPot size={25} weight="duotone" aria-hidden="true"/></div><div className="sample-cook-copy"><div className="sample-cook-meta"><span className="sample-cook-badge">SAMPLE COOK</span><span className="sample-service"><i/>Service connected</span></div><h2>Explore the sample cook.</h2><p>Simulated probes and a recorded cook. Explore the readings, timeline, and journal.</p><p className="sample-cook-note">Finish and save this sample before starting your own cook.</p></div><button className="secondary sample-cook-action" onClick={()=>onNavigate('setup')}>Explore setup<ArrowRight size={17} aria-hidden="true"/></button></article>;
 return <article className={'next-action feature-card '+(alarm||stale||!online?'attention':'')}><div className="panel-heading"><p className="eyebrow">YOUR NEXT MOVE</p><span>{online?'Cook service connected':'Service offline'}</span></div>
 {!online?<><h2>Reconnect before relying on this view.</h2><p>Readings and actions may have changed. Background alerts depend on the cook service staying awake and running.</p></>:alarm?<><h2>{alarm.label}</h2><p>A cook alarm needs attention. Check the food or sensor before dismissing it.</p><div className="button-row"><button className="primary" disabled={busy} onClick={()=>act('alarm_ack',{id:alarm.id},'Acknowledged')}>Acknowledge</button><button className="secondary" disabled={busy} onClick={()=>act('alarm_snooze',{id:alarm.id,seconds:300},'Snoozed 5 minutes')}>Snooze 5m</button><button className="text-button" onClick={()=>onNavigate('alerts')}>Details</button></div></>:stale?<><h2>Check {stale.name}’s reading.</h2><p>The last sample is stale. Confirm the probe connection or enter a fresh manual measurement.</p><button className="primary" onClick={()=>onNavigate('meal')}>Check reading</button></>:task?<><h2>{isRunning?'Check progress: ':due?'Start: ':'Up next: '}{task.name}</h2><p>{isRunning?`Started ${when(task.started)}. ${!task.estimate_elapsed?Math.ceil(task.remaining/60)+'m estimated remaining.':'Estimate elapsed; confirm completion.'}`:`Planned ${when(task.planned_start)} · ${task.duration/60}m estimate.`} {task.resource?`Uses ${task.slots} space unit${task.slots>1?'s':''}.`:''}</p>{task.slack_seconds<0&&<p className="late">About {Math.ceil(-task.slack_seconds/60)}m behind the serving plan. Review durations or change the goal.</p>}<div className="button-row"><button className="primary" disabled={busy||!online} onClick={()=>act(isRunning?'task_done':'task_start',isRunning?{id:task.id,done:true}:{id:task.id},isRunning?'Step completed':'Step started')}>{isRunning?'Confirm step done':'Start step'}</button><button className="secondary" onClick={()=>onNavigate('plan')}>Review timeline</button></div></>:<><h2>{data.active?'Keep an eye on the cook.':'Plan your next meal.'}</h2><p>{tasks.length?'Finish the required steps to unlock the next action.':data.active?'Add foods and a plan to get coordinated next actions.':'Pick your foods, grill space and serving time.'}</p><button className="primary" onClick={()=>onNavigate(data.active?'plan':'setup')}>{data.active?'Build a timeline':'Guided setup'}</button></>}
 {!compact&&<p className="muted small">Actions guide your cook; they never control the grill. Completion always needs your confirmation.</p>}</article>
}
export function PhoneView({data,act,busy,online,onNavigate}){
 const unit=data.unit;const value=v=>Math.round(unit==='C'?(v-32)*5/9:v);
 return <section className="feature-screen phone-screen"><div className="section-heading"><div><p className="eyebrow">AT THE GRILL</p><h1>{data.active?.name||'Your cook companion'}</h1><p className="muted">Serving {data.plan.serve_at?new Date(data.plan.serve_at*1000).toLocaleString():'goal not set'} · {online?'Connected':'Offline'}</p></div></div><NextAction data={data} act={act} busy={busy} online={online} onNavigate={onNavigate} compact/><div className="phone-readings">{data.foods.map(f=><article className={'feature-card '+(!f.reading?.fresh?'stale-reading':'')} key={f.id}><div className="panel-heading"><h2>{f.name}</h2><span>{f.finished?'Finished':data.plan.tasks.find(t=>t.food===f.id&&t.started&&!t.completed)?.name||f.steps[f.stage]}</span></div><strong className="phone-temperature">{f.reading?.value_f!=null?value(f.reading.value_f):'—'}<sup>°{unit}</sup></strong><p>Target {value(f.target_f)}°{unit} · {f.zone}</p><p className="muted small">{f.reading?`${f.reading.fresh?'Recent':'STALE'} ${f.reading.source} · ${when(f.reading.at)}`:'No reading yet'}</p>{!f.finished&&!f.device&&<form className="inline-form" onSubmit={e=>{e.preventDefault();act('food_reading',{id:f.id,value:new FormData(e.currentTarget).get('value'),unit},'Reading saved')}}><input type="number" step="0.1" name="value" required aria-label={'Phone temperature for '+f.name} placeholder={`Reading °${unit}`}/><button className="primary" disabled={busy||!online}>Log</button></form>}</article>)}</div><p className="muted small">This view needs a reachable service. It does not provide offline alerts or background phone push. See Integrations for authenticated HTTPS access.</p></section>
}
