import {cardPhoto} from './cardPhotos';
import React,{useState} from 'react';
import {Pepper} from '@phosphor-icons/react/dist/csr/Pepper';
import {peppers,pepperSources,heatBand,shuLabel,heatPosition} from './pepperCatalog';
import './meal-explorers.css';
import './peppers.css';
function HeatRange({pepper}){return <div className="pepper-scale" aria-label={`${pepper.name}: ${shuLabel(pepper)}, logarithmic heat scale`}><span style={{left:`${heatPosition(pepper.min)}%`,width:`${Math.max(1,heatPosition(pepper.max)-heatPosition(pepper.min))}%`}}/></div>}
export function PepperExplorer({download}){
 const [selected,setSelected]=useState('poblano'),[query,setQuery]=useState(''),[region,setRegion]=useState('All'),[heat,setHeat]=useState('All'),[sort,setSort]=useState('heat'),[compare,setCompare]=useState([]),[message,setMessage]=useState('');
 const item=peppers.find(p=>p.id===selected);
 const filtered=peppers.filter(p=>(region==='All'||p.region===region)&&(heat==='All'||heatBand(p)===heat)&&`${p.name} ${p.region} ${p.profile} ${p.form} ${p.pairs.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='hot'?b.max-a.max:a.max-b.max);
 const toggle=p=>{if(compare.includes(p.id)){setCompare(compare.filter(id=>id!==p.id));setMessage('')}else if(compare.length<3){setCompare([...compare,p.id]);setMessage('')}else setMessage('Compare up to three peppers. Remove one to choose another.')};
 const exportGuide=()=>download([`OmaPit · ${item.name}`,`${shuLabel(item)} · ${heatBand(item)}`,`Culinary association: ${item.region}`,item.context,`Flavor: ${item.profile}`,`Form: ${item.form}`,`At the grill: ${item.grill}`,`Pair with: ${item.pairs.join(', ')}`,`Heat reference: ${pepperSources[item.source]}`,`Regional context: ${pepperSources[item.contextSource||item.source]}`,'Published heat ranges vary by reference, cultivar and growing conditions. These are not measurements of your pepper. Grill guidance is an original starting suggestion, not a tested recipe.'].join('\n\n'),`omapit-pepper-${item.id}.txt`,'text/plain');
 return <section className="meal-explorer pepper-explorer"><header className="explore-hero explore-hero-peppers"><div><p className="eyebrow">THE FLAVOR ATLAS / PEPPERS</p><h1>Find your kind of heat.</h1><p>From sweet blistered peppers to fiery finishing sauces. Explore flavor, place and the Scoville scale.</p></div><span className="explore-hero-number"><Pepper size={52} weight="duotone" aria-hidden="true"/><small>10 PEPPERS / A WORLD OF FLAVOR</small></span></header>
 <div className="explore-toolbar pepper-toolbar"><label>Find a pepper<input aria-label="Search peppers" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ancho, Mexico, fruity…"/></label><label>Regional association<select aria-label="Filter pepper region" value={region} onChange={e=>setRegion(e.target.value)}>{['All',...new Set(peppers.map(p=>p.region))].map(r=><option key={r}>{r}</option>)}</select></label><label>Heat level<select aria-label="Filter pepper heat" value={heat} onChange={e=>setHeat(e.target.value)}>{['All','Sweet','Mild','Medium','Hot','Very hot','Superhot'].map(h=><option key={h}>{h}</option>)}</select></label><label>Sort<select aria-label="Sort peppers" value={sort} onChange={e=>setSort(e.target.value)}><option value="heat">Mildest first</option><option value="hot">Hottest first</option><option value="name">Name</option></select></label></div>
 <div className="pepper-results"><span>{filtered.length} of {peppers.length} peppers</span><button className="text-button" onClick={()=>{setQuery('');setHeat('All');setRegion('All');setSort('heat')}}>Reset filters</button></div>
 <div className="explore-workbench"><div className="explore-library"><div className="explore-cards pepper-cards">{filtered.map(p=><article key={p.id} className={'pepper-card photo-card '+(selected===p.id?'selected':'')} style={{...cardPhoto('peppers',p.id),'--pepper-color':p.color}}><button className="pepper-card-main" aria-pressed={selected===p.id} onClick={()=>setSelected(p.id)}><span className="pepper-card-top"><Pepper size={32} weight="duotone" aria-hidden="true"/><span>{heatBand(p)}</span></span><h2>{p.name}</h2><p>{p.region}</p><strong>{shuLabel(p)}</strong><HeatRange pepper={p}/><span className="pepper-flavor">{p.profile}</span></button><button className="pepper-compare-toggle" aria-pressed={compare.includes(p.id)} aria-label={`Compare ${p.name}`} onClick={()=>toggle(p)}>{compare.includes(p.id)?'✓ Comparing':'+ Compare'}</button></article>)}</div>{!filtered.length&&<p className="explore-empty">No matching peppers. Try another heat level or reset your filters.</p>}
 <section className="pepper-comparison" aria-label="Pepper comparison"><div className="explore-section-title"><h2>Compare the heat</h2><span>{compare.length} / 3</span></div><p className="muted small">Ranges overlap. The same variety can differ from fruit to fruit.</p>{compare.length?<div className="pepper-compare-scroll"><table><caption className="sr-only">Selected pepper heat and flavor comparison</caption><thead><tr><th scope="col">Pepper</th><th scope="col">Scoville range</th><th scope="col">Flavor / region</th><th scope="col">Remove</th></tr></thead><tbody>{compare.map(id=>{const p=peppers.find(x=>x.id===id);return <tr key={id}><th scope="row">{p.name}</th><td>{shuLabel(p)}<HeatRange pepper={p}/></td><td>{p.profile}<small>{p.region}</small></td><td><button className="text-button" aria-label={`Remove ${p.name} from comparison`} onClick={()=>toggle(p)}>×</button></td></tr>})}</tbody></table></div>:<p className="explore-empty">Choose “Compare” on up to three pepper cards.</p>}<p className="pepper-scale-note">Bars use a logarithmic 0–1,000,000 SHU scale; equal spacing means powers of ten, not equal heat increments. Heat labels are OmaPit browsing groups.</p>{message&&<p role="status" className="explore-message">{message}</p>}</section></div>
 <aside className="explore-inspector pepper-inspector"><p className="eyebrow">PEPPER FIELD NOTES</p><h2>{item.name}</h2><div className="pepper-heat-number">{shuLabel(item)}<span>{heatBand(item)} · published range</span></div><HeatRange pepper={item}/><p className="explore-profile">{item.profile}</p><div className="explore-detail"><span>01 / PLACE & FORM</span><b>{item.region}</b><p>{item.context}</p><p>{item.form} · <i>{item.species}</i></p></div><div className="explore-detail"><span>02 / AT THE GRILL</span><p>{item.grill}</p></div><div className="explore-detail"><span>03 / PAIR IT WITH</span><div className="explore-chips">{item.pairs.map(p=><span key={p}>{p}</span>)}</div></div><button className="secondary" onClick={exportGuide}>Export pepper guide ↗</button><a className="explore-source" href={pepperSources[item.source]} target="_blank" rel="noreferrer">Scoville reference ↗</a>{item.contextSource&&<a className="explore-source" href={pepperSources[item.contextSource]} target="_blank" rel="noreferrer">Regional context ↗</a>}<p className="small muted">SHU varies with cultivar, ripeness and growing conditions. Published sources may give different ranges; this is not a measurement of your batch.</p></aside></div>
 <footer className="explore-footer">Regional labels indicate culinary associations, not exclusive origins. Grill notes are original suggestions. For hot chiles, wear gloves, avoid touching eyes and avoid breathing fumes when heating. Artwork is illustrative.</footer></section>
}
