export const pepperSources={
 cornell:'https://cals.cornell.edu/school-integrative-plant-science/school-sections/horticulture-section/outreach-and-extension/pandemic-vegetable-gardening/pandemic-vegetable-gardening-2021-archive/pepper-secrets',
 florida:'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/peppers-by-scoville-units/',
 nmsu:'https://pubs.nmsu.edu/_circulars/CR706.pdf'
};
// Ranges follow the named extension reference, not laboratory measurements of a user's pepper.
// Flavor, pairings and grill guidance are OmaPit editorial suggestions.
export const peppers=[
 {id:'bell',name:'Bell pepper',min:0,max:0,region:'Global',species:'C. annuum',color:'#c75136',profile:'Sweet · juicy · crisp',context:'A versatile sweet pepper used across many cuisines.',grill:'Quarter and remove the core. Grill skin-side down until blistered, then finish until tender.',pairs:['Steak','Sausage','Vegetable skewers'],form:'Fresh; green or fully ripe colors',source:'cornell'},
 {id:'anaheim',name:'Anaheim',min:500,max:1500,region:'U.S. Southwest',species:'C. annuum',color:'#92a75f',profile:'Gentle heat · grassy · mellow',context:'A California Anaheim-type chile; related New Mexican cultivars are distinct, not interchangeable names.',grill:'Blister whole over direct heat, turning often. Peel if desired and fold into a relish.',pairs:['Burgers','Chicken','Corn'],form:'Fresh green or ripe red',source:'cornell',contextSource:'nmsu'},
 {id:'poblano',name:'Poblano',min:1000,max:2000,region:'Mexico',species:'C. annuum',color:'#597849',profile:'Earthy · green · rich',context:'A Mexican chile. The ripe, dried form is ancho.',grill:'Char whole and turn until the skin blisters. Peel, split and use for a stuffed pepper or grilled salsa.',pairs:['Beef','Black beans','Cheese'],form:'Fresh poblano; ripe and dried as ancho',source:'florida'},
 {id:'jalapeno',name:'Jalapeño',min:3000,max:8000,region:'Mexico',species:'C. annuum',color:'#7c9c44',profile:'Bright · grassy · punchy',context:'A staple of Mexican salsas. Ripe, wood-smoked jalapeños become chipotles.',grill:'Halve for stuffed peppers or blister whole for salsa. Use a grill basket for small pieces.',pairs:['Brisket','Cream cheese','Corn'],form:'Fresh green or red; smoked as chipotle',source:'cornell',contextSource:'florida'},
 {id:'serrano',name:'Serrano',min:10000,max:25000,region:'Mexico',species:'C. annuum',color:'#539460',profile:'Clean · sharp · green',context:'Associated with the mountains of Puebla and Hidalgo, Mexico.',grill:'Blister briefly in a basket and chop into a finishing salsa. Start with a small amount.',pairs:['Tacos','Pork','Tomatillo'],form:'Fresh green or ripe red',source:'florida'},
 {id:'cayenne',name:'Cayenne',min:30000,max:50000,region:'French Guiana',species:'C. annuum',color:'#d85e37',profile:'Direct heat · lean · peppery',context:'Named for Cayenne in French Guiana; often sold dried or ground.',grill:'Use a little dried cayenne in a rub. Add fresh chopped chile to a sauce after a small trial batch.',pairs:['Ribs','Chicken','Dry rubs'],form:'Fresh, dried, flakes or powder',source:'cornell',contextSource:'florida'},
 {id:'thai',name:'Thai chile',min:50000,max:100000,region:'Southeast Asia',species:'C. annuum',color:'#e6563d',profile:'Lively · sharp · intense',context:'Widely grown in South and Southeast Asia; its ancestral roots are in the Americas.',grill:'Use sparingly in a finishing sauce. Tiny pods are best kept in a basket rather than directly on the grate.',pairs:['Chicken','Lime','Fish'],form:'Fresh red or green; dried',source:'florida'},
 {id:'habanero',name:'Habanero',min:150000,max:350000,region:'Mexico / Americas',species:'C. chinense',color:'#e69a3e',profile:'Fruity · floral · fiery',context:'Its spread links Peru, Mexico and other parts of the Americas.',grill:'Build a small fruit-and-chile glaze; taste a diluted portion before coating food. Keep the glaze away from prolonged direct flame.',pairs:['Pork','Pineapple','Mango'],form:'Fresh, dried or sauce',source:'cornell',contextSource:'florida'},
 {id:'scotch-bonnet',name:'Scotch bonnet',min:100000,max:325000,region:'Caribbean',species:'C. chinense',color:'#e8ab41',profile:'Tropical · fragrant · very hot',context:'Closely associated with Caribbean jerk sauces and marinades.',grill:'Mince a small amount into a jerk-style marinade. Offer extra chile sauce separately so guests can choose their heat.',pairs:['Chicken','Allspice','Thyme'],form:'Fresh bonnet-shaped pods',source:'cornell',contextSource:'florida'},
 {id:'ghost',name:'Ghost pepper',min:850000,max:1000000,region:'India',species:'C. chinense × C. frutescens',color:'#c94537',profile:'Intense · lingering · superhot',context:'Bhut jolokia is associated with Assam, India.',grill:'For experienced cooks: use a tiny measured amount in a separate test sauce. Avoid heating concentrated chile indoors or over a smoky flame.',pairs:['Small-batch hot sauce'],form:'Fresh, dried or powder',source:'cornell',contextSource:'florida'}
];
export const heatBand=p=>p.max===0?'Sweet':p.max<=2000?'Mild':p.max<=25000?'Medium':p.max<=100000?'Hot':p.max<=350000?'Very hot':'Superhot';
export const shuLabel=p=>p.min===p.max?`${p.max.toLocaleString('en-US')} SHU`:`${p.min.toLocaleString('en-US')}–${p.max.toLocaleString('en-US')} SHU`;
export const heatPosition=n=>n===0?0:Math.log10(Math.max(1,n))/6*100;
