import {extraSauceIngredients,extraSauceStyles} from './bbqExpansion.js';
// Regional descriptions are source-backed; blend ratios are OmaPit starting points,
// not reproductions of restaurant recipes. Volumes add approximately, not exactly.
const guide='https://amazingribs.com/tested-recipes/barbecue-sauce-recipes/benchmark-barbecue-sauces/';
const regional='https://bbqchamps.com/the-different-regional-barbecue-styles/';
export const ingredients={
 ...extraSauceIngredients,
 ketchup:{name:'Ketchup',role:'base'}, vinegar:{name:'Apple cider vinegar',role:'tang'}, mustard:{name:'Yellow mustard',role:'base',allergens:'Check label for mustard and other allergens'}, mayo:{name:'Mayonnaise',role:'base',allergens:'Usually egg; check label'}, water:{name:'Water',role:'thin'}, sugar:{name:'Brown sugar, packed',role:'sweet',dry:true}, molasses:{name:'Molasses',role:'sweet'}, honey:{name:'Honey',role:'sweet'}, worcestershire:{name:'Worcestershire sauce',role:'savory',allergens:'Often fish; may contain soy or wheat; check label'}, pepper:{name:'Black pepper',role:'spice',dry:true}, chili:{name:'Chili flakes',role:'heat',dry:true}, hot:{name:'Hot sauce',role:'heat'}, garlic:{name:'Garlic powder',role:'spice',dry:true}, salt:{name:'Salt',role:'spice',dry:true}, lemon:{name:'Lemon juice',role:'tang'}, horseradish:{name:'Prepared horseradish',role:'spice'}
};
export const sauceStyles=[
 {id:'kc',name:'Kansas City Red',region:'Kansas City · Missouri',family:'Tomato',profile:'Sweet · rich · tangy',pairs:['Pork','Beef','Chicken','Vegetables'],description:'A thick tomato sauce with sweetness and an acidic finish.',tradition:'Mixed smoked meats and ribs; a sweet red sauce is a familiar companion.',use:'Brush on near the end or offer at the table. Sugary sauces can scorch over direct heat.',method:'Whisk together. Simmer gently until the sugar dissolves and the texture suits you; stir often. Cool before tasting and adjust.',source:regional,recipe:{ketchup:50,vinegar:15,sugar:14,molasses:8,water:8,worcestershire:3,garlic:1,pepper:.7,salt:.3}},
 {id:'east',name:'Eastern Carolina Vinegar',region:'Eastern North Carolina',family:'Vinegar',profile:'Sharp · peppery · light',pairs:['Pork','Chicken'],description:'A thin vinegar-and-pepper style without a tomato base.',tradition:'Whole-hog barbecue, chopped pork, and a bright vinegar dressing.',use:'Toss a little through pulled pork, then serve extra separately.',method:'Whisk until the sugar and salt dissolve. Let the flavors mingle in the refrigerator; shake before serving.',source:guide,recipe:{vinegar:75,water:17,sugar:4,hot:2,pepper:1,chili:.5,salt:.5}},
 {id:'lexington',name:'Lexington Dip',region:'Piedmont · North Carolina',family:'Vinegar',profile:'Tangy · light tomato · pepper',pairs:['Pork'],description:'Vinegar-led with a small tomato contribution.',tradition:'Pork shoulder barbecue with a light red dip.',use:'Dress chopped pork lightly; keep some clean sauce for the table.',method:'Whisk together, warm gently to dissolve the sugar, then cool and taste.',source:guide,recipe:{vinegar:57,ketchup:22,water:12,sugar:5,hot:2,pepper:1,salt:.5,chili:.5}},
 {id:'gold',name:'Carolina Gold',region:'South Carolina',family:'Mustard',profile:'Mustard · bright · sweet-tart',pairs:['Pork','Chicken','Vegetables'],description:'Mustard leads this tangy golden sauce.',tradition:'Pork barbecue with mustard-based sauce, alongside other local sauce traditions.',use:'Serve with pork or use a light finishing coat on chicken.',method:'Whisk together, warm gently to blend, then cool. Taste before adding more salt: prepared mustard varies.',source:'https://destination-bbq.com/sc-bbq-survey-2025/',recipe:{mustard:50,vinegar:22,honey:15,water:8,worcestershire:3,pepper:1,garlic:.7,salt:.3}},
 {id:'white',name:'Alabama White',region:'Northern Alabama',family:'Creamy',profile:'Creamy · tangy · peppery',pairs:['Chicken','Pork','Vegetables'],description:'A mayonnaise-based sauce associated with Big Bob Gibson’s barbecue.',tradition:'Smoked chicken and a tangy white finishing sauce.',use:'Use as a finishing sauce or dip. Keep refrigerated; do not treat it as shelf-stable.',method:'Whisk cold ingredients until smooth. Refrigerate, then taste. Do not simmer this mayonnaise-based blend.',source:'https://bigbobgibson.com/products/original-white-sauce',recipe:{mayo:65,vinegar:20,lemon:6,water:4,horseradish:3,pepper:1,sugar:.7,salt:.3}},
 {id:'memphis',name:'Memphis Red',region:'Memphis · Tennessee',family:'Tomato',profile:'Tangy · savory · gently sweet',pairs:['Pork','Chicken'],description:'A tomato-forward companion to Memphis pork barbecue.',tradition:'Pork ribs and shoulder, including dry-rubbed ribs with sauce offered separately.',use:'Keep the rub in the spotlight; offer sauce on the side or as a thin finishing coat.',method:'Whisk and simmer gently, stirring often. Cool and taste; thin with a little water if needed.',source:regional,recipe:{ketchup:42,vinegar:25,water:18,sugar:8,worcestershire:4,hot:1,garlic:1,pepper:.7,salt:.3}},
 {id:'texas',name:'Texas Pepper Mop',region:'Texas-inspired',family:'Savory',profile:'Peppery · thin · savory',pairs:['Beef','Pork','Goat'],description:'A thin, pepper-led blend for a lighter sauce approach.',tradition:'Central Texas emphasizes smoked beef; sauce practices vary widely across Texas.',use:'Use a clean brush for finishing. This is an original Texas-inspired blend, not a universal Texas recipe.',method:'Whisk together and warm gently. Taste after cooling; adjust pepper and dilution to suit the meat.',source:regional,recipe:{water:40,vinegar:30,ketchup:16,worcestershire:8,sugar:3,pepper:1.5,garlic:1,salt:.5}},
 {id:'kentucky',name:'Kentucky Black Dip',region:'Western Kentucky',family:'Savory',profile:'Dark · savory · vinegar',pairs:['Lamb','Goat','Beef'],description:'A dark vinegar-and-Worcestershire-inspired dip.',tradition:'Mutton barbecue is a distinctive western Kentucky tradition.',use:'A savory alternative for lamb or goat. Check Worcestershire ingredients for dietary restrictions.',method:'Whisk together and warm gently to dissolve the sugar. Cool, taste and adjust the dilution.',source:'https://www.moonlite.com/images/Media_Kit.pdf',recipe:{water:49,vinegar:30,worcestershire:15,sugar:3,pepper:1,hot:1,garlic:.5,salt:.5}}
 ,...extraSauceStyles
];
export const foodTypes={venison:{name:'Venison roast',yield:65},pork:{name:'Pork shoulder / pulled pork',yield:55},beef:{name:'Brisket / beef roast',yield:55},steak:{name:'Beef steak',yield:75},ribs:{name:'Bone-in ribs',yield:45},chicken:{name:'Boneless chicken',yield:75},lamb:{name:'Lamb / goat roast',yield:65},vegetables:{name:'Vegetables',yield:85}};
export const ML_PER_TBSP=14.7868,ML_PER_CUP=236.588;
const finite=(x,min,max,fallback)=>Number.isFinite(Number(x))&&x!==''?Math.min(max,Math.max(min,Number(x))):fallback;
export function estimateSauce({guests,portion,reserve,foods}){
 const people=finite(guests,1,200,1),perPerson=finite(portion,0,8,2),buffer=finite(reserve,0,100,15);
 const rows=foods.map(f=>{const kg=finite(f.weight,0,1000,0)*(f.unit==='lb'?.45359237:1);const cooked=kg*(f.basis==='raw'?finite(f.yield,1,100,60)/100:1);return {...f,cookedKg:cooked,glazeMl:cooked*finite(f.coats,0,5,0)*finite(f.rate,0,500,60)}});
 const tableMl=people*perPerson*ML_PER_TBSP,glazeMl=rows.reduce((sum,f)=>sum+f.glazeMl,0),reserveMl=(tableMl+glazeMl)*buffer/100;
 return {rows,tableMl,glazeMl,reserveMl,totalMl:tableMl+glazeMl+reserveMl,cookedKg:rows.reduce((sum,f)=>sum+f.cookedKg,0)};
}
export function scaleBlend(recipe,totalMl){const entries=Object.entries(recipe).filter(([id,v])=>ingredients[id]&&Number.isFinite(Number(v))&&Number(v)>0);const sum=entries.reduce((s,[,v])=>s+Number(v),0);return entries.map(([id,v])=>({id,...ingredients[id],percent:Number(v)/sum*100,ml:totalMl*Number(v)/sum}));}
export function formatVolume(ml){return `${Math.round(ml)} mL · ${(ml/ML_PER_CUP).toFixed(2)} US cups`;}
export function recipeText({name,style,recipe,estimate,guests,portion,reserve}){return `${name}\nInspired by ${style.name} · ${style.region}\n\nApproximate batch: ${formatVolume(estimate.totalMl)}\n${guests} guests · ${portion} US tbsp per guest at the table · ${reserve}% reserve\nTable: ${Math.round(estimate.tableMl)} mL\nGlaze: ${Math.round(estimate.glazeMl)} mL\nReserve: ${Math.round(estimate.reserveMl)} mL\n\nFood assumptions\n${estimate.rows.map(f=>`${foodTypes[f.type]?.name}: ${f.weight} ${f.unit} ${f.basis}; ${f.basis==='raw'?f.yield+'% edible cooked yield':'cooked edible weight'}; ${f.coats} coats at ${f.rate} mL/kg/coat`).join('\n')}\n\nIngredients (approximate volumes; not weights)\n${scaleBlend(recipe,estimate.totalMl).map(i=>`${i.name}: ${i.dry?(i.ml/(ML_PER_TBSP/3)).toFixed(2)+' US tsp':i.ml<15?(i.ml/(ML_PER_TBSP/3)).toFixed(2)+' US tsp':Math.round(i.ml)+' mL'} (${i.percent.toFixed(1)}%)`).join('\n')}\n\n${style.method}\nTaste a small sample before scaling. Added ingredient volumes do not guarantee final yield; measure after mixing and top up as needed. Custom ingredient changes may need a different preparation method.\nReserve clean table sauce before any raw-meat contact. Refrigerate perishable sauce. No canning or shelf-stability claim.\nRegional source: ${style.source}\nFood handling: https://ask.fsis.usda.gov/article/Can-you-reuse-meat-marinade\nOmaPit original starting blend; untested kitchen recipe.\n`;}
