import React,{useState} from 'react';
import './slicing-diagrams.css';
const guides={
 grain:{tile:0,title:'Across the grain',alt:'Raw flank steak with horizontal muscle fibers on a cutting board.',steps:['Find the fibers','Cross the fibers','Shorter fibers per bite'],notes:['Follow the fine muscle strands. Grill marks do not indicate the grain.','The slice line crosses the fibers at roughly 90°. A bias angle is a separate choice.','Thin slices shorten the fibers further. Adjust thickness to the cooked tenderness.'],legend:['Blue · muscle fibers','Gold · slice lines']},
 trim:{tile:1,title:'Lift the silver skin',alt:'Tenderloin with a lifted membrane and a shallow boning blade.',steps:['Lift a small tab','Stay just underneath','Work away from your hand'],notes:['Expose a membrane tab so you can maintain gentle tension.','Keep the blade shallow, with its edge angled slightly toward the membrane. This is not a fixed-degree angle.','Use controlled strokes. Keep the hand holding the membrane outside the projected blade path.'],legend:['Blue · lifted membrane','Gold · shallow blade path']},
 seams:{tile:2,title:'Follow the natural seam',alt:'Two beef muscles opened along a connective seam.',steps:['Find the seam','Open the attachment','Preserve each muscle'],notes:['The pale connective layer marks the division between muscles.','Open gently, then make short cuts only at connective attachments.','Follow the actual anatomy; the illustrated seam is an example, not a universal cut map.'],legend:['Blue · connective seam','Gold · attachment cuts']},
 steaks:{tile:3,title:'Even steak portions',alt:'A strip loin with evenly portioned steaks beside it.',steps:['Set the thickness','Repeat the spacing','Keep portions consistent'],notes:['Choose thickness for your recipe and cut; no single thickness fits every steak.','Keep successive cuts parallel and evenly spaced across the loin.','Even thickness helps the portions cook consistently. Keep raw portions chilled.'],legend:['Gold · portion lines','Equal gaps · consistent thickness']},
 brisket:{tile:4,title:'Two muscles, two grain directions',alt:'Separated smoked brisket flat and point, oriented differently on a board.',steps:['Identify each muscle','Slice the flat','Turn for the point'],notes:['This example shows the flat and point already separated. Their muscle fibers run in different directions.','Inspect the flat’s actual fibers and slice across them. Surface bark can obscure the grain.','Reorient the point, then cross its own grain. These arrows show an example orientation.'],legend:['Blue · each muscle’s grain','Gold · perpendicular slice lines']},
 poultry:{tile:5,title:'Carve the breast on the board',alt:'Removed cooked poultry breast with serving slices and a carving knife.',steps:['Remove the breast','Lay it securely','Slice for serving'],notes:['This is the serving step after removing cooked breast meat from the carcass, not a raw joint-disassembly diagram.','Place the breast flat on a stable board. Find the muscle grain before cutting.','Make smooth, even crosswise slices across the actual grain; keep skin with the slices when practical.'],legend:['Gold · serving slices','Boneless breast · after removal']},
 care:{tile:6,title:'A stable board, a controlled edge',alt:'Chef knife on a wooden board supported by a nonslip mat.',steps:['Secure the board','Control the blade','Protect the edge'],notes:['A nonslip base helps prevent the board moving under load.','Keep the supporting hand clear of the blade path. No hand grip is depicted in this illustration.','Hone or sharpen according to the blade maker’s instructions; do not guess an edge angle from this overhead view.'],legend:['Blue · board support','Gold · blade / handle orientation']}
};
export function SlicingDiagram({lesson}){
 const [show,setShow]=useState(true),[step,setStep]=useState(0),[large,setLarge]=useState(false);const d=guides[lesson]||guides.grain;
 const id='slice-arrow-'+lesson, col=d.tile%4,row=Math.floor(d.tile/4);
 const cut=(x,y1=26,y2=75)=> <path key={x+'-'+y1} d={`M${x} ${y1}V${y2}`} stroke="#ffd082" strokeWidth=".8" strokeDasharray="2 1.5"/>;
 return <figure className={'slicing-diagram '+(large?'diagram-large':'')}><div className="slicing-toolbar"><span>VISUAL FIELD GUIDE</span><div><button aria-pressed={show} onClick={()=>setShow(!show)}>{show?'Hide':'Show'} guides</button><button aria-pressed={large} onClick={()=>setLarge(!large)}>{large?'Standard view':'Enlarge'}</button></div></div><div className="slicing-photo" role="img" aria-label={d.alt+' '+d.legend.join('. ')} style={{backgroundPosition:`${col/3*100}% ${row*100}%`}}>
 {show&&<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><marker id={id} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#80d9ed"/></marker></defs><g className="diagram-guide-lines">
 {lesson==='grain'&&<><path d="M22 48H76" stroke="#80d9ed" strokeWidth="1" markerEnd={`url(#${id})`}/>{step>0&&[36,45,54,63].map(x=>cut(x,32,67))}</>}
 {lesson==='trim'&&<><ellipse cx="52" cy="40" rx="19" ry="6" stroke="#80d9ed" strokeWidth=".7" fill="none"/>{step>0&&<path d="M65 47L39 43" stroke="#ffd082" strokeWidth="1" strokeDasharray="2 1.5"/>}</>}
 {lesson==='seams'&&<><path d="M51 26Q46 48 51 75" fill="none" stroke="#80d9ed" strokeWidth="1" strokeDasharray="2 1"/>{step>0&&[38,51,64].map(y=><path key={y} d={`M47 ${y}h7`} stroke="#ffd082" strokeWidth="1.2"/>)}</>}
 {lesson==='steaks'&&[30,38,46].slice(0,step+1).map(x=>cut(x,28,72))}
 {lesson==='brisket'&&<><path d="M16 49H43M84 33V65" stroke="#80d9ed" strokeWidth="1" markerEnd={`url(#${id})`}/>{step>0&&[24,30,36].map(x=>cut(x,33,66))}{step>1&&[43,51,59].map(y=><path key={y} d={`M70 ${y}h23`} stroke="#ffd082" strokeWidth=".8" strokeDasharray="2 1.5"/>)}</>}
 {lesson==='poultry'&&step>0&&[44,50,56].map(x=>cut(x,33,65))}
 {lesson==='care'&&<><path d="M8 87H44" stroke="#80d9ed" strokeWidth="1"/>{step>0&&<path d="M31 24L74 61" stroke="#ffd082" strokeWidth=".8" strokeDasharray="2 1.5"/>}</>}
 </g></svg>}
 <div className="slicing-image-title"><span>0{step+1} / {d.steps[step]}</span><strong>{d.title}</strong></div></div><div className="slicing-legend">{d.legend.map((text,i)=><span key={text}><i style={{background:i?'#ffd082':'#80d9ed'}}/>{text}</span>)}</div><div className="slicing-step-tabs" aria-label="Diagram steps">{d.steps.map((name,i)=><button key={name} aria-pressed={step===i} onClick={()=>setStep(i)}><b>0{i+1}</b>{name}</button>)}</div><figcaption><p aria-live="polite">{d.notes[step]}</p><small>Generated instructional illustration. Guide lines explain the technique; identify the actual fibers, membrane and joints on your own cut.</small></figcaption></figure>
}
