export const themeKey='omapit-theme-v1';
export const themes=[
 {id:'omarchy',name:'Omarchy',tag:'Your desktop, your fire.',description:'Classic charcoal with cool blue readings and warm ember accents.',base:'#151922',panel:'#202536',ink:'#c0caf5',muted:'#a9b1d6',accent:'#e0af68',secondary:'#7aa2f7',heading:'inherit',tile:5},
 {id:'steakhouse',name:'Steakhouse',tag:'Bold flavor. Refined.',description:'Oxblood leather, walnut, antique brass and warm ivory typography.',base:'#1c1312',panel:'#2b1d1b',ink:'#f5e9d5',muted:'#c9b7a0',accent:'#dfb96c',secondary:'#ed9d8b',heading:'Georgia, serif',tile:0},
 {id:'backyard',name:'Backyard BBQ',tag:'Good food. Good company.',description:'Sunlit cedar, cream linen, sage enamel and picnic-weave details.',base:'#eee6d5',panel:'#faf4e6',ink:'#292f25',muted:'#59624f',accent:'#395d43',secondary:'#87432a',heading:'Georgia, serif',tile:1},
 {id:'football',name:'American Football',tag:'Smoke brings us together.',description:'Midnight stadium green, pebbled leather and clean chalk-white lines.',base:'#101c19',panel:'#1d302a',ink:'#edf4e9',muted:'#b3cabc',accent:'#91d2a4',secondary:'#e6b884',heading:'inherit',tile:2},
 {id:'thanksgiving',name:'Thanksgiving',tag:'Gratitude tastes good.',description:'Warm parchment, burnished copper, russet leaves and autumn light.',base:'#f0dfc1',panel:'#faf0dc',ink:'#382617',muted:'#70513a',accent:'#93401c',secondary:'#624c2f',heading:'Georgia, serif',tile:3},
 {id:'christmas',name:'Christmas',tag:'Good food brings us closer.',description:'Evergreen velvet, burgundy, antique gold and delicate pine detail.',base:'#0e201c',panel:'#19352c',ink:'#f5ecda',muted:'#bbd0bf',accent:'#e4c280',secondary:'#e8a09a',heading:'Georgia, serif',tile:4},
];
export function readTheme(storage){try{const id=(storage||localStorage).getItem(themeKey);return themes.some(t=>t.id===id)?id:'omarchy'}catch{return 'omarchy'}}
export function applyTheme(id,root=document.documentElement){const t=themes.find(t=>t.id===id)||themes[0];root.dataset.omapitTheme=t.id;const values={'--background':t.base,'--foreground':t.ink,'--accent':t.accent,'--accent-secondary':t.secondary,'--amber':t.accent,'--blue':t.secondary,'--muted':t.muted,'--line':`color-mix(in srgb, ${t.ink} 22%, ${t.base})`,'--theme-panel':t.panel,'--theme-heading':t.heading,'--theme-tile-x':`${t.tile%3*50}%`,'--theme-tile-y':`${Math.floor(t.tile/3)*100}%`};for(const [key,value] of Object.entries(values))root.style.setProperty(key,value);root.style.colorScheme=['backyard','thanksgiving'].includes(t.id)?'light':'dark';return t;}
